Repository avinashkranjan/Amazing-Python-Scripts, pull requests merged in 2021-04, with the labels that each got.

#775 Unzip file
  Unzip file/Readme.md
  Unzip file/script.py
Labels: Approved, GSSOC21, Level1

#759 Added Google Meet Scheduler
  Google-Meet-Scheduler/README.md
  Google-Meet-Scheduler/images/1.PNG
  Google-Meet-Scheduler/images/10.png
  Google-Meet-Scheduler/images/11.jpg
  Google-Meet-Scheduler/images/12.jpg
  Google-Meet-Scheduler/images/13.jpg
  Google-Meet-Scheduler/images/3.png
  Google-Meet-Scheduler/images/4.PNG
  Google-Meet-Scheduler/images/5.PNG
  Google-Meet-Scheduler/images/6.PNG
  Google-Meet-Scheduler/images/7.PNG
  Google-Meet-Scheduler/images/8.PNG
  Google-Meet-Scheduler/images/9.PNG
  Google-Meet-Scheduler/requirements.txt
  Google-Meet-Scheduler/script.py
Labels: Approved, GSSOC21, Level2

#776 Codes on turtle graphics
  Codes on Turtle Graphics/Animated_Robot.py
  Codes on Turtle Graphics/Kaleido-spiral.png
  Codes on Turtle Graphics/Kaleido-spiral.py
  Codes on Turtle Graphics/README.md
  Codes on Turtle Graphics/Robot.png
Labels: Approved, GSSOC21, Level2

#791 Added Youtube Trending Feed Scrapper
  Youtube Trending Feed Scrapper/ReadMe.md
  Youtube Trending Feed Scrapper/scrap_reader.py
  Youtube Trending Feed Scrapper/youtube_scrapper.py
Labels: Approved, GSSOC21, Level3

#745 🚀Added Gmplot
  Gmplot-Track the Route/LatLong.csv
  Gmplot-Track the Route/README.md
  Gmplot-Track the Route/main.py
Labels: Approved, GSSOC21, Level2

#721 Password manager GUI
  Password-Manager-GUI/README.md
  Password-Manager-GUI/passwords.py
Labels: Approved, GSSOC21, Level2

#795 Typing Speed test file added
  Typing-Speed-Test/README.md
  Typing-Speed-Test/sentences.txt
  Typing-Speed-Test/speed_test.py
Labels: Approved, GSSOC21, Level2

#802 Dev.to scraper
  Dev.to Scraper/README.md
  Dev.to Scraper/requirements.txt
  Dev.to Scraper/scraper.py
Labels: Approved, GSSOC21, Level3

#743 Negative/ghost image
  Ghost filter/Ghost filter code.py
  Ghost filter/Images/Ghost Filtered Image_.jpg
  Ghost filter/Images/Real Photo.jpg
  Ghost filter/README.md
Labels: Approved, GSSOC21, Level2

#766 Desktop Voice Assistant
  Desktop-Voice-assistant/READme.md
  Desktop-Voice-assistant/requirements.txt
  Desktop-Voice-assistant/voice_assistant.py
Labels: Approved, GSSOC21, Level2

#782 Issue 778
  Guess the Countries/README.md
  Guess the Countries/blank.png
  Guess the Countries/country_names.csv
  Guess the Countries/guessed_countries.png
  Guess the Countries/main.py
  Guess the Countries/world_map.gif
Labels: Approved, GSSOC21, Level2

#786 Image to speech
  Imagetospeech/Readme.md
  Imagetospeech/image_to_speech.py
Labels: Approved, GSSOC21, Level2

#792 Minesweeper Script
  MineSweeper/minesweeper.py
  MineSweeper/readme.md
Labels: Approved, GSSOC21, Level3

#796 Terminal Hangman
  Terminal Hangman/Readme.md
  Terminal Hangman/T_hangman.py
  Terminal Hangman/data.txt
Labels: Approved, GSSOC21, Level1

#860 Qr code
  QR-code-Genrator/README.md
  QR-code-Genrator/employee_qr/emp_101.png
  QR-code-Genrator/employee_qr/emp_102.png
  QR-code-Genrator/main.py
  QR-code-Genrator/requirement.txt
Labels: Approved, GSSOC21, Level2

#855 Added Photo_to_Ascii
  Photo To Ascii/README.md
  Photo To Ascii/photo_to_ascii.py
Labels: Approved, GSSOC21, Level1

#837 Added script for Codechef Scrapper
  Codechef Scrapper/README.md
  Codechef Scrapper/codechef.py
  Codechef Scrapper/requirements.txt
Labels: Approved, GSSOC21, Level3

#836 Bag of words model
  Bag of words model/README.md
  Bag of words model/bow.py
Labels: Approved, GSSOC21, Level2

#832 Distance conversion GUI
  Distance Conversion GUI/README.md
  Distance Conversion GUI/dist_conv1.PNG
  Distance Conversion GUI/dist_conv2.PNG
  Distance Conversion GUI/dist_conv3.PNG
  Distance Conversion GUI/distance_conversion.py
Labels: Approved, GSSOC21, Level2

#839 Monster jobs scraper
  MonsterJobs Scraper/README.md
  MonsterJobs Scraper/requirements.txt
  MonsterJobs Scraper/scraper.py
Labels: Approved, GSSOC21, Level2

#838 Added Script for Scripts.json
  script_updater.py
Labels: Approved, GSSOC21, Level2

#824 SMS automation
  SMS Automation/Readme.md
  SMS Automation/script.py
Labels: Approved, GSSOC21, Level2

#808 Added Age Calculator GUI
  Age-Calculator-GUI/README.md
  Age-Calculator-GUI/age_calc_gui.py
Labels: Approved, GSSOC21, Level1

#801 Stopwatch GUI
  Stopwatch GUI/README.md
  Stopwatch GUI/stopwatch1.png
  Stopwatch GUI/stopwatch2.png
  Stopwatch GUI/stopwatch_gui.py
Labels: Approved, GSSOC21, Level2

#797 Facebook bot
  Automate Facebook bot/Readme.md
  Automate Facebook bot/script.py
Labels: Approved, GSSOC21, Level2

#857 Ipl statistics gui
  IPL Statistics GUI/README.md
  IPL Statistics GUI/ipl.py
  IPL Statistics GUI/requirements.txt
Labels: Approved, GSSOC21, Level2

#746 Added Battery Notification Script
  Battery-Notification/Battery-Notification.py
  Battery-Notification/README.md
Labels: Approved, GSSOC21, Level1

#848 Tarot reader
  Tarot Reader/README.md
  Tarot Reader/tarot.txt
  Tarot Reader/tarot_card_reader.py
Labels: Approved, GSSOC21, Level1

#852 Corona cases Time series forecasting #828
  corona cases forecasting/README.md
  corona cases forecasting/Results/plot1.png
  corona cases forecasting/Results/plot2.png
  corona cases forecasting/Results/plot3.png
  corona cases forecasting/main.py
  corona cases forecasting/requirements.txt
Labels: Approved, GSSOC21, Level3

#874 #868 PDF reoder added
  PDF-Tools/README.md
  PDF-Tools/main.py
Labels: Approved, GSSOC21, Level1

#879 #867 Image background subractor added
  Image_Background_Subtractor/BG_Subtractor.py
  Image_Background_Subtractor/README.md
  Image_Background_Subtractor/requirements.txt
Labels: Approved, GSSOC21, Level2

#888 Image viewing GUI
  Image_Viewing_GUI/Readme.md
  Image_Viewing_GUI/script.py
Labels: Approved, GSSOC21, Level2

#899 Udemy scraper
  Udemy Scraper/README.md
  Udemy Scraper/display.py
  Udemy Scraper/fetcher.py
  Udemy Scraper/requirements.txt
Labels: Approved, GSSOC21, Level2

#897 Adding guessing game with tkinter code and readme
  Guessing_Game_GUI/README.md
  Guessing_Game_GUI/guessing_game_tkinter.py
Labels: Approved, GSSOC21, Level1

#895 Random password generator
  Random Password Generator/README.md
  Random Password Generator/script.py
Labels: Approved, GSSOC21, Level2

#889 AWS management Script
  AWS Management Scripts/AWS Automation Script for AWS endorsement management/Readme.md
  AWS Management Scripts/AWS Automation Script for AWS endorsement management/awsLambda.py
  AWS Management Scripts/AWS Automation Script for AWS endorsement management/ec2.py
  AWS Management Scripts/AWS Automation Script for AWS endorsement management/rds.py
  AWS Management Scripts/AWS testing Script/Readme.md
  AWS Management Scripts/AWS testing Script/agentMain.py
  AWS Management Scripts/AWS testing Script/awsHandler.py
  AWS Management Scripts/AWS testing Script/awsTester.py
Labels: Approved, GSSOC21, Level3

#880 Mini google assistant
  Mini Google Assistant/Mini google assistant.py
  Mini Google Assistant/README.md
Labels: Approved, GSSOC21, Level2

#854 Brick game
  Brick Breaker game/Readme.md
  Brick Breaker game/brick_breaker.py
Labels: Approved, GSSOC21, Level2

#851 TicTacToe-GUI using Pygame 🐍
  TicTacToe-GUI/README.md
  TicTacToe-GUI/TicTacToe.py
Labels: Approved, GSSOC21, Level2

#891 Fast algorithm
  Fast Algorithm (Corner Detection)/Fast_Algorithm.py
  Fast Algorithm (Corner Detection)/Output.png
  Fast Algorithm (Corner Detection)/Readme.md
  Fast Algorithm (Corner Detection)/input.jpg
Labels: Approved, GSSOC21, Level2

#830 Health log book
  Health_Log_Book/README.md
  Health_Log_Book/database.py
  Health_Log_Book/main.py
Labels: Approved, GSSOC21, Level2

#926 Added code for Waterfall,Funnel,Ternary and Contour Plots
  Data-Visualization/Contour Plots/contour_plot.py
  Data-Visualization/Contour Plots/contourplot.png
  Data-Visualization/FunnelChart/FunnelChart.png
  Data-Visualization/FunnelChart/FunnelCharts.py
  Data-Visualization/README.md
  Data-Visualization/TernaryPlots/TernaryPlot.py
  Data-Visualization/TernaryPlots/ternaryplot.png
  Data-Visualization/WaterfallChart/WaterFall.png
  Data-Visualization/WaterfallChart/Waterfall.py
Labels: Approved, GSSOC21, Level2

#921 Piglatin_translator scripts
  Piglatin_Translator/README.md
  Piglatin_Translator/piglatin.py
Labels: Approved, GSSOC21, Level1

#918 ORB algorithm
  ORB Algorithm/ORB_Algorithm.py
  ORB Algorithm/Readme.md
Labels: Approved, GSSOC21, Level2

#907 Added Todolist Cli-Version
  TODO (CLI-VER)/README.md
  TODO (CLI-VER)/todolist.py
Labels: Approved, GSSOC21, Level1

#903 Twitter Scraper using snscrape
  Twitter_Scraper_without_API/README.md
  Twitter_Scraper_without_API/display_hashtags.py
  Twitter_Scraper_without_API/fetch_hashtags.py
  Twitter_Scraper_without_API/requirements.txt
Labels: Approved, GSSOC21, Level2

#896 Project addition : Link preview
  .gitignore
  Link-Preview/README.md
  Link-Preview/linkPreview.py
  Link-Preview/requirements.txt
Labels: Approved, GSSOC21, Level2

#892 Expense tracker
  Expense Tracker/Readme.md
  Expense Tracker/script.py
Labels: Approved, GSSOC21, Level2

#919 #913 Codeforces_Problem_Scraper Added
  Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
  Coderforces_Problem_Scrapper/README.md
  Coderforces_Problem_Scrapper/requirements.txt
Labels: Approved, GSSOC21, Level2

#925 Sentiment Detector
  Script to check Sentiment/Readme.md
  Script to check Sentiment/script.py
Labels: Approved, GSSOC21, Level2

#948 Instagram follow not follow
  Instagram Follow- NotFollow/README.md
  Instagram Follow- NotFollow/main.py
Labels: Approved, GSSOC21, Level1

#943 Nse stocks GUI
  NSE Stocks GUI/README.md
  NSE Stocks GUI/requirements.txt
  NSE Stocks GUI/stocks.py
Labels: Approved, GSSOC21, Level2

#939 Leetcode Scrapper
  LeetCode-Scrapper/README.md
  LeetCode-Scrapper/ques.py
  LeetCode-Scrapper/requirements.txt
Labels: Approved, GSSOC21, Level3
