Repository avinashkranjan/Amazing-Python-Scripts, pull requests merged in 2021-03, with the labels that each got.

#504 Digital Clock
  Digital Clock/Clock.py
  Digital Clock/README.md
  Digital Clock/Sample Output.png
Labels: Approved, GSSOC21, Level1

#461 Update SCRIPTS.md
  SCRIPTS.md
Labels: Approved, GSSOC21, Level1, documentation

#553 DIRECTORY TREE GENERATOR
  Directory Tree Generator/README.md
  Directory Tree Generator/Screenshot (142).png
  Directory Tree Generator/requirements.txt
  Directory Tree Generator/tree.py
Labels: Approved, GSSOC21, Level1

#449 Improved text-to-speech.py
  Text-To-Speech/README.md
  Text-To-Speech/text-to-speech.py
Labels: Approved, GSSOC21, Level2

#543 Added Movie-Info-Telegram-Bot
  Movie-Info-Telegram-Bot/.env.example
  Movie-Info-Telegram-Bot/README.md
  Movie-Info-Telegram-Bot/bot.py
  Movie-Info-Telegram-Bot/requirements.txt
Labels: Approved, GSSOC21, Level2

#463 Created Network troubleshooter as per issue #457
  Network-troubleshooter/README.md
  Network-troubleshooter/ipreset.py
Labels: Approved, GSSOC21, Level2

#470 add(Script): IMDB Scraper
  IMDB-Scraper/README.md
  IMDB-Scraper/scraper.py
Labels: Approved, GSSOC21, Level2

#477 added hangman game
  Hangman-Game/README.md
  Hangman-Game/hangman0.png
  Hangman-Game/hangman1.png
  Hangman-Game/hangman2.png
  Hangman-Game/hangman3.png
  Hangman-Game/hangman4.png
  Hangman-Game/hangman5.png
  Hangman-Game/hangman6.png
  Hangman-Game/main.py
  Hangman-Game/program.py
  Hangman-Game/requirements.txt
  Hangman-Game/words.txt
Labels: Approved, GSSOC21, Level3

#499 Added the Shortest Path Finder gssoc'21
  Shortest-Path-Finder (GUI)/1. Marked Start and End Point.png
  Shortest-Path-Finder (GUI)/2. Made Obstacles.png
  Shortest-Path-Finder (GUI)/3. Shortest Path marked in Purple by the Algorithm.png
  Shortest-Path-Finder (GUI)/README.md
  Shortest-Path-Finder (GUI)/Shortest Path Finder.py
Labels: Approved, GSSOC21, Level3

#502 Spreadsheet Automation
  Spreadsheet_Automation/PriceBook.xlsx
  Spreadsheet_Automation/Purchases - Home B.xlsx
  Spreadsheet_Automation/Readme.md
  Spreadsheet_Automation/script.py
Labels: Approved, GSSOC21, Level2

#513 issue #498 slideshare downloader added
  Slideshare downloader/README.md
  Slideshare downloader/requirements.txt
  Slideshare downloader/slideshare_downloader.py
Labels: Approved, GSSOC21, Level2

#517 Added Dice roll simulator
  Dice-Roll-Simulator/README.md
  Dice-Roll-Simulator/dice_roll_simulator.py
  Dice-Roll-Simulator/imgs/die1.png
  Dice-Roll-Simulator/imgs/die2.png
  Dice-Roll-Simulator/imgs/die3.png
  Dice-Roll-Simulator/imgs/die4.png
  Dice-Roll-Simulator/imgs/die5.png
  Dice-Roll-Simulator/imgs/die6.png
  Dice-Roll-Simulator/program.py
Labels: Approved, GSSOC21, Level2

#542 Enhancing Data Visualization Scripts #515
  Data-Visualization/Bar Plotting/program.py
  Data-Visualization/BarChart/RevisedBarChart.png
  Data-Visualization/BarChart/bar_chart.py
  Data-Visualization/BubbleChart/BubbleChart.png
  Data-Visualization/BubbleChart/bubble_chart.py
  Data-Visualization/HeatMap/HeatMap.png
  Data-Visualization/HeatMap/heat_maps.py
  Data-Visualization/Histogram Plotting/program.py
  Data-Visualization/HistogramPlot/Histogram.png
  Data-Visualization/HistogramPlot/histogram.py
  Data-Visualization/Line Plotting/program.py
  Data-Visualization/LineChart/LineChart.png
  Data-Visualization/LineChart/line_chart.py
  Data-Visualization/Pie Chart Plotting/program.py
  Data-Visualization/PieChart/RevisedPieChart.png
  Data-Visualization/PieChart/pie_chart.py
  Data-Visualization/README.md
  Data-Visualization/Scatter Plotting/program.py
  Data-Visualization/ScatterPlot/ScatterPlot.png
  Data-Visualization/ScatterPlot/scatter_plot.py
Labels: Approved, GSSOC21, Level3

#514 Issue 501 (Facial Expression Recognition)
  Facial-Expression-Recognition/face_crop.py
  Facial-Expression-Recognition/haarcascade_frontalface_alt.xml
  Facial-Expression-Recognition/label.py
  Facial-Expression-Recognition/label_image.py
  Facial-Expression-Recognition/readme.md
  Facial-Expression-Recognition/retrain.py
Labels: Approved, GSSOC21, Level2

#535 Video to audio converter
  Video-To-Audio(CLI-Ver)/README.md
  Video-To-Audio(CLI-Ver)/video_to_audio.py
Labels: Approved, GSSOC21, Level2

#527 Extracting text from a real time captured image (#497)
  Realtime Text Extraction/Readme.md
  Realtime Text Extraction/Realtime Text Extraction.py
  Realtime Text Extraction/Realtime_Text_Extracion.ipynb
Labels: Approved, GSSOC21, Level3

#538 Translator python
  Translator Script/README.md
  Translator Script/Translation.py
Labels: Approved, GSSOC21, Level1

#532 Email Validation Script #297
  Email-Validator/README.md
  Email-Validator/email_verification.py
Labels: Approved, GSSOC21, Level2

#529 Invisibility_Cloak is added
  Invisibility_Cloak/Invisibility_Cloak.py
  Invisibility_Cloak/README.md
Labels: Approved, GSSOC21, Level3

#525 Script to extract emails from a website content
  extracting-emails-from-website/emails-from-website.py
  extracting-emails-from-website/readme.md
Labels: Approved, GSSOC21, Level2

#518 Quiz Application - GUI
  Quiz-GUI/README.md
  Quiz-GUI/quiztime.py
Labels: Approved, GSSOC21, Level2

#516 Music player robin
  Music-Player-App/assests/images/001-volume.png
  Music-Player-App/assests/images/002-mute.png
  Music-Player-App/assests/images/pause.png
  Music-Player-App/assests/images/play.png
  Music-Player-App/assests/images/rewind.png
  Music-Player-App/assests/images/stop.png
  Music-Player-App/assests/rockerz.ico
  Music-Player-App/assests/screenshot/Screenshot.png
  Music-Player-App/main.py
  Music-Player-App/readme.MD
Labels: Approved, GSSOC21, Level3

#537 Added the python-script for Colour detection project
  Color_detection/Color_detection.py
  Color_detection/Readme.md
  Color_detection/colorpic.jpg
  Color_detection/colors.csv
Labels: Approved, GSSOC21, Level2

#555 add-flipkart-price-alert-with-changes
  Flipkart-price-alert/README.md
  Flipkart-price-alert/requirements.txt
  Flipkart-price-alert/track.py
Labels: Approved, GSSOC21, Level2

#557 Instagram Liker Bot
  Instagram Liker Bot/Instagram_Liker_Bot.py
  Instagram Liker Bot/readMe.md
Labels: Approved, GSSOC21, Level2

#561 Added virtual paint
  Virtual Paint/README.md
  Virtual Paint/virtual_paint.py
Labels: Approved, GSSOC21, Level3

#591 Added Blackjack
  Blackjack/README.md
  Blackjack/blackjack.py
Labels: Approved, GSSOC21, Level1

#592 Translator gui
  Translator-GUI/README.md
  Translator-GUI/requirements.txt
  Translator-GUI/translator.py
Labels: Approved, GSSOC21, Level3

#595 Added Currency convertor - GUI based
  Currency Convertor - GUI based/Currency_convertor_GUI.py
  Currency Convertor - GUI based/Readme.md
Labels: Approved, GSSOC21, Level2

#597 Cartooning Image
  Cartooning Image/README.md
  Cartooning Image/cartoon.png
  Cartooning Image/cartooneffect.py
Labels: Approved, GSSOC21, Level2

#603 Caesar cipher
  Caesar-Cipher/README.md
  Caesar-Cipher/caesar_cipher.py
  Caesar-Cipher/output.png
Labels: Approved, GSSOC21, Level2

#615 Added bubble sort simulation
  Bubble-Sort-Visualization/README.md
  Bubble-Sort-Visualization/bubble_sort.py
Labels: Approved, GSSOC21, Level2

#624 Issue 482
  Attachment_Downloader/README.md
  Attachment_Downloader/attachment.py
Labels: Approved, GSSOC21, Level2

#634 $connect 4 game
  Connect-4 game/Connect-4.py
  Connect-4 game/READme.md
Labels: Approved, GSSOC21, Level2

#635 Added Auto B'day Wisher - gssoc'21 #623
  Auto Birthday Wisher/Auto B'Day Wisher.py
  Auto Birthday Wisher/README.md
  Auto Birthday Wisher/data.xlsx
  Auto Birthday Wisher/emailReceived.jpg
Labels: Approved, GSSOC21, Level2

#630 Face mask
  Face-Mask-Detection/Dataset.rar
  Face-Mask-Detection/Sample-images/Method.jpg
  Face-Mask-Detection/Sample-images/Sample_image_1.jpg
  Face-Mask-Detection/Sample-images/Sample_image_2.jpg
  Face-Mask-Detection/Sample-images/Sample_image_3.jpg
  Face-Mask-Detection/face_mask_detection_using_cnn.py
  Face-Mask-Detection/readme.md
Labels: Approved, GSSOC21, Level3

#680 issue #636 @censor_word_detection
  Censor word detection/README.md
  Censor word detection/censor_word_detection.py
Labels: Approved, GSSOC21, Level2

#674 News scrapper
  News_Scrapper/README.md
  News_Scrapper/scrapper.py
Labels: Approved, GSSOC21, Level2

#669 Tweet fetch
  Tweet-Fetcher/README.md
  Tweet-Fetcher/display.py
  Tweet-Fetcher/fetcher.py
  Tweet-Fetcher/requirements.txt
Labels: Approved, GSSOC21, Level3

#665 Applying bitwise operations
  Applying Bitwise Operations/Applying Bitwise operations.py
  Applying Bitwise Operations/Readme.md
Labels: Approved, GSSOC21, Level2

#662 Sticky Notes
  sticky notes/README.md
  sticky notes/main.py
Labels: Approved, GSSOC21, Level3

#656 Added contour detection
  Contour-Detection/README.md
  Contour-Detection/live_contour_det.py
Labels: Approved, GSSOC21, Level3

#648 Added Desktop DrinkWater Notification
  Desktop-drinkWater-Notification/Readme.md
  Desktop-drinkWater-Notification/icon.ico
  Desktop-drinkWater-Notification/main.py
  Desktop-drinkWater-Notification/output.jpg
Labels: Approved, GSSOC21, Level1

#645 added ImageToSketch folder
  ImageToSketch/README.md
  ImageToSketch/haarcascade_frontalface_default.xml
  ImageToSketch/images-trial/hulk.jpg
  ImageToSketch/sketchScript.py
  ImageToSketch/sketches/hulk/hulk(blured).png
  ImageToSketch/sketches/hulk/hulk(final).png
  ImageToSketch/sketches/hulk/hulk(gray).png
  ImageToSketch/sketches/hulk/hulk(inverted).png
  ImageToSketch/webcam/data/example.jpg
Labels: Approved, GSSOC21, Level2

#641 Calendar - GUI
  Calendar GUI/Calendar for the year.png
  Calendar GUI/Calendar_gui.py
  Calendar GUI/Input Calendar.png
  Calendar GUI/README.md
Labels: Approved, GSSOC21, Level2

#638 adding heart disease prediction
  Heart Disease Prediction/README.md
  Heart Disease Prediction/heart_model.pkl
  Heart Disease Prediction/requirements.txt
  Heart Disease Prediction/script.py
Labels: Approved, GSSOC21, Level2

#637 Price Comparison and Checker
  Price Comparison and Checker/Readme.md
  Price Comparison and Checker/Requirements.txt
  Price Comparison and Checker/price_comparison.py
Labels: Approved, GSSOC21, Level2

#622 🚀Added Image Processing
  Image Processing/ImageCompressing.py
  Image Processing/ImageTransposing.py
  Image Processing/ImgEnhancing.py
  Image Processing/README.md
  Image Processing/default.jpg
Labels: Approved, GSSOC21, Level2

#610 Edge detection using open cv
  Edge Detection/Edge_Detection.ipynb
  Edge Detection/Edge_Detection.py
  Edge Detection/Readme.md
  Edge Detection/Sample_Input.jpg
  Edge Detection/Sample_Output.png
Labels: Approved, GSSOC21, Level2

#605 Create Bitcoin mining Script
  BitCoin Mining/BitCoin_Mining.py
  BitCoin Mining/README.md
Labels: Approved, GSSOC21, Level2

#601 Added Body Detection
  Body Detection/README.md
  Body Detection/detection.py
  Body Detection/haarcascade_fullbody.xml
Labels: Approved, GSSOC21, Level3

#598 Select Stocks by Volume Increases
  Select Stocks by volume Increase/Readme.md
  Select Stocks by volume Increase/companylist.csv
  Select Stocks by volume Increase/script.py
Labels: Approved, GSSOC21, Level3

#682 Modification in Face-Detection/face-detect.py
  Face-Detection/v2/README.md
  Face-Detection/v2/face_detectv2.py
  Face-Detection/v2/haarcascade_eye.xml
  Face-Detection/v2/haarcascade_frontalface_default.xml
Labels: Approved, GSSOC21, Level2

#735 Dictionary GUI
  Dictionary-GUI/README.md
  Dictionary-GUI/dictionary.py
  Dictionary-GUI/requirements.txt
Labels: Approved, GSSOC21, Level2

#678 Update temp_sign_up_tool.py
  Temporary-Sign-Up-Tool/temp_sign_up_tool.py
Labels: Approved, GSSOC21, Level0

#716 Adding the python script for image editor and the readme.md file
  Image editor python script/Image_editing_script.py
  Image editor python script/readme.md
Labels: Approved, GSSOC21, Level3

#707 Plagiarism-Checker
  Plagiarism-Checker/README.md
  Plagiarism-Checker/assets/Capture1.PNG
  Plagiarism-Checker/file1.txt
  Plagiarism-Checker/file2.txt
  Plagiarism-Checker/file3.txt
  Plagiarism-Checker/file4.txt
  Plagiarism-Checker/plagiarism.py
Labels: Approved, GSSOC21, Level3

#701 🚀 Rock paper scissor
  StonePaperScissor - GUI/README.md
  StonePaperScissor - GUI/StonePaperScissors.py
Labels: Approved, GSSOC21, Level2

#699 added Morse Code Translator
  Morse_Code_Translator/Morse_Code_Translator.py
  Morse_Code_Translator/README.md
Labels: Approved, GSSOC21, Level2

#698 LinkedIn Connections Scrapper
  Linkedin_Connections_Scrapper/ReadMe.md
  Linkedin_Connections_Scrapper/script.py
Labels: Approved, GSSOC21, Level3

#691 Image Base steganography script added
  Steganography/README.md
  Steganography/steganography.py
Labels: Approved, GSSOC21, Level2

#683 Wikipedia summary GUI
  Wikipedia-Summary-GUI/README.md
  Wikipedia-Summary-GUI/requirements.txt
  Wikipedia-Summary-GUI/summary.py
Labels: Approved, GSSOC21, Level3

#681 Update face-detect.py
  Face-Detection/v3/README.md
  Face-Detection/v3/face_detectv3.py
  Face-Detection/v3/haarcascade_frontalface.xml
Labels: Approved, GSSOC21, Level2

#676 Issue #450
  Insta-Bot-Follow-SendMsg/README.md
  Insta-Bot-Follow-SendMsg/instabot.py
Labels: Approved, GSSOC21, Level2

#654 Modified the website(gh-pages branch)
  website/home.css
  website/home.html
  website/scripts.css
  website/scripts.html
Labels: Approved, GSSOC21, Level3

#667 Added Eyes Detection
  Eye Detection/README.md
  Eye Detection/eyes.py
  Eye Detection/haarcascade_eye.xml
Labels: Approved, GSSOC21, Level2

#620 Added YouTube video downloader
  YouTube-Video-Downloader/README.md
  YouTube-Video-Downloader/youtube_vid_dl.py
Labels: Approved, GSSOC21, Level2

#584 Added Message_Spam_Detection script
  Message_Spam_Detection/Cleaned_Dataset.csv
  Message_Spam_Detection/Dataset_Cleaning.py
  Message_Spam_Detection/Message_Spam_Detection.py
  Message_Spam_Detection/README.MD
  Message_Spam_Detection/dataset.csv
Labels: Approved, GSSOC21, Level3

#672 Feature/covid stats
  Covid India Stats App/README.md
  Covid India Stats App/app.py
Labels: Approved, GSSOC21, Level3

#650 Air pollution prediction
  Air pollution prediction/CodeAP.py
  Air pollution prediction/README.md
Labels: Approved, GSSOC21, Level1

#692 Added number plate detector
  Num-Plate-Detector/README.md
  Num-Plate-Detector/car.jpeg
  Num-Plate-Detector/number_plate.py
Labels: Approved, GSSOC21, Level2

#695 Paint Application GUI
  Paint Application/README.md
  Paint Application/paint.py
  Paint Application/requirements.txt
Labels: Approved, GSSOC21, Level3

#728 Added your meeting buddy
  Your Meeting Buddy/Gmeet_buddy.py
  Your Meeting Buddy/Readme.md
Labels: Approved, GSSOC21, Level2

#772 Calcy
  Smart calcy/Readme.md
  Smart calcy/Smart_calcy.py
Labels: Approved, GSSOC21, Level2

#758 Watermark Maker(For Images)
  Watermark Maker(On Image)/README.md
  Watermark Maker(On Image)/Test_Image2.png
  Watermark Maker(On Image)/Watermark_maker.py
  Watermark Maker(On Image)/test_image.jpg
Labels: Approved, GSSOC21, Level2

#750 POS removal from hindi text
  Remove_POS_hindi_text/Input.png
  Remove_POS_hindi_text/Only_Hindi.txt
  Remove_POS_hindi_text/Output.png
  Remove_POS_hindi_text/README.md
  Remove_POS_hindi_text/Tagged_Hindi_Corpus.txt
  Remove_POS_hindi_text/hindi_POS_tag_removal.py
Labels: Approved, GSSOC21, Level3

#747 Added weight converter
  Weight-Converter-GUI/README.md
  Weight-Converter-GUI/weight_con_gui.py
Labels: Approved, GSSOC21, Level2

#708 Make a banner image for repository
  website/AmazingPyScripts.jpeg
Labels: Approved, GSSOC21, Level3

#736 Pdf2Text
  PDF2Text/Readme.md
  PDF2Text/script.py
Labels: Approved, GSSOC21, Level1

#670 Adding Contributors list
  website/home.html
Labels: Approved, GSSOC21, Level2

#734 Desktop notification
  Desktop News Notifier/Readme.md
  Desktop News Notifier/script.py
Labels: Approved, GSSOC21, Level2

#773 Simple Python IDE using Tkinter
  Simple Python IDE using Tkinter/README.md
  Simple Python IDE using Tkinter/script.py
Labels: Approved, GSSOC21, Level2
