Repository avinashkranjan/Amazing-Python-Scripts, pull requests merged in 2021-05, with the labels that each got.

#963 Added 'Master Script' base JSON DB
  Master Script/Script.py
  Master Script/datastore.json
Labels: Approved, GSSOC21, Level3, Urgent

#936 Added contact us files
  website/home.html
  website/images/python_background.png
  website/images/python_logo.png
  website/page-contact.css
  website/page_contactUs.html
Labels: Approved, GSSOC21, Level2

#1025 Action db update
  .github/pull_request_template.md
  .github/scripts/Update_Database.py
  .github/workflows/database_auto_updater.yml
  Master Script/datastore.json
  Master Script/manual db updater.py
Labels: Urgent, next review needed

#1002 Added Base-N-Calc Files
  Base-N_Calc/Readme.md
  Base-N_Calc/data/GSSOC.png
  Base-N_Calc/script.py
Labels: Approved, GSSOC21, Level2

#861 Added finger counter
  Finger-Counter/FingerImages/1.png
  Finger-Counter/FingerImages/2.png
  Finger-Counter/FingerImages/3.png
  Finger-Counter/FingerImages/4.png
  Finger-Counter/FingerImages/5.png
  Finger-Counter/FingerImages/6.png
  Finger-Counter/HandTrackingModule.py
  Finger-Counter/README.md
  Finger-Counter/finger_counter.py
  Finger-Counter/requirements.txt
Labels: Approved, GSSOC21, Level2

#934 ▶Buttons pygame
  Pygame-Buttons/ExampleButtons.py
  Pygame-Buttons/README.md
  Pygame-Buttons/main.py
  Pygame-Buttons/requirements.txt
  Pygame-Buttons/retry_button.png
Labels: Approved, GSSOC21, Level2

#1042 PDF to Word Converter
  PDFToWord/README.md
  PDFToWord/main.py
  PDFToWord/requirements.txt
Labels: Approved, GSSOC21, Level1

#1031 Add linear search visualizer
  Linear Search Visualizer/README.md
  Linear Search Visualizer/script.py
Labels: Approved, GSSOC21, Level2

#964 Added files for pwned or not
  Pwned_or_not_GUI/README.md
  Pwned_or_not_GUI/pwned_passwords_GUI.py
  Pwned_or_not_GUI/requirements.txt
Labels: Approved, GSSOC21, Level2

#1030 Updating Scripts contributors on Website with implementation of search bar
  css/home.css
  css/page-contact.css
  css/scripts.css
  datastore.json
  images/AmazingPyScripts.jpeg
  images/python_background.png
  images/python_logo.png
  index.html
  js/contributors.js
  js/scripts.js
  page_contactUs.html
  scripts.html
  website/home.html
  website/page-contact.css
  website/page_contactUs.html
  website/scripts.css
  website/scripts.html
Labels: Approved, GSSOC21, Level3, Urgent

#1026 Blood Content Alcohol
  Blood Alcohol Content/Blood_Alcohol_Content.py
  Blood Alcohol Content/README.md
Labels: Approved, GSSOC21, Level1

#935 Firebase Management Scipts
  FirebaseScripts/CredentialsHelper.py
  FirebaseScripts/Readme.md
  FirebaseScripts/credentials.env
  FirebaseScripts/firebase_authentications.py
  FirebaseScripts/firebase_database.py
  FirebaseScripts/firebase_storage.py
  FirebaseScripts/requirements.txt
Labels: Approved, GSSOC21, Level3

#990 Beat board
  Beat-Board/README.md
  Beat-Board/Sounds/Kick.wav
  Beat-Board/Sounds/Pad1.wav
  Beat-Board/Sounds/Pad2.wav
  Beat-Board/Sounds/Pad3.wav
  Beat-Board/Sounds/Pad4.wav
  Beat-Board/Sounds/Pad5.wav
  Beat-Board/Sounds/Pad6.wav
  Beat-Board/Sounds/hiHat.wav
  Beat-Board/Sounds/snare.wav
  Beat-Board/beatBoard.py
  Beat-Board/requirements.txt
Labels: Approved

#952 twitterSentimentalAnalysisScript
  TwitterTweetSentimentalAnalysis/Model.py
  TwitterTweetSentimentalAnalysis/Readme.md
  TwitterTweetSentimentalAnalysis/app.py
  TwitterTweetSentimentalAnalysis/requirements.txt
Labels: Approved, GSSOC21, Level2

#958 TextSentimentalAnalysisScipt
  Text_Sentimental_Analysis_Script_with_GUI/Model.py
  Text_Sentimental_Analysis_Script_with_GUI/Readme.md
  Text_Sentimental_Analysis_Script_with_GUI/__init__.py
  Text_Sentimental_Analysis_Script_with_GUI/app.py
  Text_Sentimental_Analysis_Script_with_GUI/images/background.png
  Text_Sentimental_Analysis_Script_with_GUI/images/search.png
  Text_Sentimental_Analysis_Script_with_GUI/textFiles/demotextfile.txt
  Text_Sentimental_Analysis_Script_with_GUI/textFiles/emotions.txt
Labels: Approved, GSSOC21, Level3

#969 Covid-19 Real Time notification
  Covid-19_Real-time_Notification/Covid.py
  Covid-19_Real-time_Notification/Notify_icon.ico
  Covid-19_Real-time_Notification/readME.md
  Covid-19_Real-time_Notification/requirements.txt
Labels: Approved, GSSOC21, Level1

#985 GST Calculator
  GST Calculator/Readme.md
  GST Calculator/script.py
Labels: Approved, GSSOC21, Level1, manual-db-update-req

#986 Speak like Yoda
  Speak-like-Yoda/README.md
  Speak-like-Yoda/Speak_Like_yoda.py
  Speak-like-Yoda/requirements.txt
Labels: Approved, GSSOC21, Level1, manual-db-update-req

#991 Implemented Audio steganography
  Audio_Steganography/Algos/Decrypt.py
  Audio_Steganography/Algos/Encrypt.py
  Audio_Steganography/Algos/__init__.py
  Audio_Steganography/Images/After.jpg
  Audio_Steganography/Images/Before.jpg
  Audio_Steganography/README.md
  Audio_Steganography/TestingCode.py
  Audio_Steganography/requirements.txt
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#994 GitHub user scraper
  Github-User-Scraper/README.md
  Github-User-Scraper/requirements.txt
  Github-User-Scraper/scraper.py
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#997 Added Rain Alert Mail Sender
  Rain Alert Mail Sender/README.md
  Rain Alert Mail Sender/main.py
  Rain Alert Mail Sender/requirements.txt
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#1110 #1103 JobScraper Added
  Job Scraper/JobScraper.py
  Job Scraper/README.md
  Job Scraper/requirements.txt
Labels: Approved, GSSOC21, Level2

#1109 Update README.md
  README.md
Labels: Approved, GSSOC21, Level0

#1008 Linkedin certifications manager
  LinkedIn-Certifications-Manager/README.md
  LinkedIn-Certifications-Manager/manager.py
  LinkedIn-Certifications-Manager/requirements.txt
Labels: Approved, GSSOC21, Level1, manual-db-update-req

#1011 Stack overflow questions scraper
  Stack-overflow-scraper/README.md
  Stack-overflow-scraper/requirements.txt
  Stack-overflow-scraper/scraper.py
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#1024 Voice Calculator
  Voice Calculator/README.md
  Voice Calculator/requirements.txt
  Voice Calculator/voiceCalc.py
Labels: Approved, GSSOC21, Level1, manual-db-update-req

#1032 Email GUI
  Email GUI/Readme.md
  Email GUI/script.py
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#1108 Added files for Facebook-DP-Downloader
  Facebook-DP-Downloader/Readme.md
  Facebook-DP-Downloader/fb_dp_downloader.py
  Facebook-DP-Downloader/requirements.txt
Labels: Approved, GSSOC21, Level1, manual-db-update-req

#1094 Added File Downloader
  File Downloader/Readme.md
  File Downloader/file_downloader.py
  File Downloader/requirements.txt
Labels: Approved, GSSOC21, Level1, manual-db-update-req

#1091 added pdf2video converter
  Pdf2Video_Converter/Readme.md
  Pdf2Video_Converter/requirements.txt
  Pdf2Video_Converter/script.py
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#1087 Pomodoro GUI
  Pomodoro_GUI/Pomodoro_gui.py
  Pomodoro_GUI/README.md
  Pomodoro_GUI/beep.wav
  Pomodoro_GUI/bg.png
  Pomodoro_GUI/requirements.txt
Labels: Approved, GSSOC21, Level3, manual-db-update-req

#1084 DNS
  DNS verifier/main.py
  DNS verifier/readme.MD
  DNS verifier/requirements.txt
Labels: Approved, GSSOC21, Level1, manual-db-update-req

#1083 Vector Calculator
  Vector_Calc/Readme.md
  Vector_Calc/requirements.txt
  Vector_Calc/script.py
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#1082 Stack Overflow Error Search Auto Tool
  Stackoverflow-Tool/README.md
  Stackoverflow-Tool/requirements.txt
  Stackoverflow-Tool/script.py
Labels: Approved, GSSOC21, Level1

#1081 Address-book
  Address-Book/Readme.md
  Address-Book/addressbook.py
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#1075 Medium scraper
  Medium-Scraper/README.md
  Medium-Scraper/requirements.txt
  Medium-Scraper/scraper.py
Labels: Approved, GSSOC21, Level3, manual-db-update-req

#1060 Real Estate Property Data #1003
  Real Estate Webscrapper/README.md
  Real Estate Webscrapper/real_estate_webscrapper.py
  Real Estate Webscrapper/requirements.txt
Labels: Approved, GSSOC21, Level1, manual-db-update-req

#1046 Twitter Video Downloader
  Twitter_Video_Downloader/Readme.md
  Twitter_Video_Downloader/requirements.txt
  Twitter_Video_Downloader/script.py
Labels: Approved, GSSOC21, Level2, manual-db-update-req

#1111 Additional scripts(Turtle Module)
  Codes on Turtle Graphics/DashedLine.png
  Codes on Turtle Graphics/Dot.png
  Codes on Turtle Graphics/DrawDashedLine.py
  Codes on Turtle Graphics/DrawShapes.py
  Codes on Turtle Graphics/DrawSpirograph.py
  Codes on Turtle Graphics/DrawSquare.py
  Codes on Turtle Graphics/HirstSpotPainting.py
  Codes on Turtle Graphics/README.md
  Codes on Turtle Graphics/RandomColorWalk.png
  Codes on Turtle Graphics/RandomColorWalk.py
  Codes on Turtle Graphics/RandomWalk.png
  Codes on Turtle Graphics/RandomWalk.py
  Codes on Turtle Graphics/Shapes.png
  Codes on Turtle Graphics/Spirograph.png
  Codes on Turtle Graphics/Square.png
  Codes on Turtle Graphics/image.jpg
Labels: Approved, GSSOC21, Level3, manual-db-update-req

#1116 Reddit scraper without API
  Reddit_Scraper_without_API/README.md
  Reddit_Scraper_without_API/display_reddit.py
  Reddit_Scraper_without_API/fetch_reddit.py
  Reddit_Scraper_without_API/requirements.txt
Labels: Approved, GSSOC21, Level2
