Repository avinashkranjan/Amazing-Python-Scripts, pull requests merged in 2023-08, with the labels that each got.

#2672 Completed 2048 game ( #2659 )
  2048 GAME/README.md
  2048 GAME/game.py
  2048 GAME/logic.py
Labels: level3, gssoc23

#2673 Rock paper scissors game completed ( #2660 )
  Rock-paper-scissors/README.md
  Rock-paper-scissors/game.py
Labels: level3, gssoc23

#2687 Telegram Bot using Python
  Telegram Bot code/README.md
  Telegram Bot code/script.py
Labels: level3, gssoc23

#2686 Open AI chatbot using python
  ChatBot using OpenAI API/README.md
  ChatBot using OpenAI API/script1.ipynb
  ChatBot using OpenAI API/script2.ipynb
  Web Scrapping using Beautiful Soup/README.md
  Web Scrapping using Beautiful Soup/code.py
Labels: level3, gssoc23

#2691 Payment Receipt Generator (#2690)
  Payment_Receipt/README.md
  Payment_Receipt/payment.py
  Payment_Receipt/receipt.pdf
Labels: level3, gssoc23

#2695 Chatbot using OpenAI API
  Chatbot  using ChatGPT OpenAI key/README.md
  Chatbot  using ChatGPT OpenAI key/script1.ipynb
  Chatbot  using ChatGPT OpenAI key/script2.ipynb
Labels: level3, gssoc23

#2668 Gomoku (Connect Five)
  Gomoku (Connect Five)/Gomoku_game.py
  Gomoku (Connect Five)/README.md
Labels: level3, gssoc23

#2639 culturally-inspired names imaginary
  Random_State_Name_Generator/README.md
  Random_State_Name_Generator/base.py
Labels: level2, gssoc23

#2635 added Tech crunch Scraper
  TechCrunch-Scraper/README.md
  TechCrunch-Scraper/requirements.txt
  TechCrunch-Scraper/techCrunch.py
Labels: level3, gssoc23

#2637 Pixel Art Generator Script Added
  Pixel Art Generator/README.md
  Pixel Art Generator/pixel_art_generator.py
  Pixel Art Generator/requirements.txt
Labels: level3, gssoc23

#2640 morphological transformations
  Morphological_transforms/ReadMe.md
  Morphological_transforms/Sample1.jpeg
  Morphological_transforms/Sample2.png
  Morphological_transforms/SampleOutput.png
  Morphological_transforms/morph_transforms.py
Labels: level3, gssoc23

#2631 feat: Screenshot Gui added with documentation
  GST Calculator/Readme.md
  GST Calculator/script.py
  Screenshot/README.md
  Screenshot/screenshot.py
  hexCalculator/README.md
  hexCalculator/hexCalculator.py
Labels: level3, gssoc23

#2429 [GSSoC'23] Advisor Application Ready
  Advisor_App/README.md
  Advisor_App/advice.py
  SCRIPTS.md
Labels: level2, gssoc23

#2430 [GSSoC'23] Open websites by Speaking
  SCRIPTS.md
  Websites_Automation/README.md
  Websites_Automation/websites.py
Labels: level2, gssoc23

#2438 Notification App(GUI)
  Notification App/ReadMe.txt
  Notification App/notification.py
Labels: level2, gssoc23

#2440 EDA on Growth of Indian Startups
  EDA_IndianStartups/StartupAnalysis.ipynb
  EDA_IndianStartups/dataset/startup_funding.csv
Labels: level3, gssoc23

#2442 Fraud Detection Script Added
  Fraud Detection/README.md
  Fraud Detection/fraud_detection.py
  Fraud Detection/requirements.txt
Labels: level3, gssoc23

#2444 Word Chain Game Script Added
  Word Chain Game/README.md
  Word Chain Game/requirements.txt
  Word Chain Game/word_chain_game.py
Labels: level2, gssoc23

#2446 Gravity Simulation Game Added
  Gravity Simulation Game/README.md
  Gravity Simulation Game/gravity_simulation_game.py
  Gravity Simulation Game/requirements.txt
Labels: level2, gssoc23

#2448 Physics Puzzle Game Script Added
  Physics Puzzle Game/README.md
  Physics Puzzle Game/physics_puzzle_game.py
  Physics Puzzle Game/requirements.txt
Labels: level2, gssoc23

#2461 Time Travel Adventure Script Added
  Time Travel Adventure/README.md
  Time Travel Adventure/requirements.txt
  Time Travel Adventure/time_travel_adventure.py
Labels: level2, gssoc23

#2480 Brick.py
  brick_game/README.md
  brick_game/brick.py
Labels: level2, gssoc23

#2481 amazon product scraper added
  Amazon_product_scraper/README.md
  Amazon_product_scraper/products.py
  Amazon_product_scraper/requirements.txt
Labels: level3, gssoc23

#2482 Web Server log analyzer
  SCRIPTS.md
  WebServer/Readme.md
  WebServer/webServerlog.py
Labels: level2, gssoc23

#2432 Gold Price Predicition
  Gold Price Prediction/Gold Price Prediction.ipynb
  Gold Price Prediction/gld_price_data.csv
Labels: level2, gssoc23

#2483 AutomatedDataReporting
  AutomatedDataReporting/Automated_Data_Reporting.py
  AutomatedDataReporting/Readme.md
  SCRIPTS.md
Labels: level2, gssoc23

#2484 Mosaic Augmentation
  Amazon_product_scraper/products.py
Labels: level2, gssoc23

#2485 Data Scraping with API
  DataScraping/Data_Scraping.py
  DataScraping/Readme.md
  SCRIPTS.md
Labels: level2, gssoc23

#2487 Cellular Automation Wars Script Added
  Cellular Automaton Wars/README.md
  Cellular Automaton Wars/cellular_automation_wars.py
  Cellular Automaton Wars/requirements.txt
Labels: level2, gssoc23

#2504 Support ChatBot
  Support Chat Bot For Your Website -  Project 9/Support Chat Bot For Website.PNG
  Support Chat Bot For Your Website -  Project 9/app.py
  Support Chat Bot For Your Website -  Project 9/constants.py
  Support Chat Bot For Your Website -  Project 9/requirements.txt
  Support Chat Bot For Your Website -  Project 9/utils.py
Labels: level2, gssoc23

#2506 AI-Powered Recipe Generator Script Added
  AI-Powered Recipe Generator/README.md
  AI-Powered Recipe Generator/recipe_generator.py
  AI-Powered Recipe Generator/requirements.txt
Labels: level2, gssoc23

#2507 Dog Breed Image Classifier Using Neural Networks with a Deployed Frontend Application
  DogBreedPrediction/DogBreedPrediction.ipynb
  DogBreedPrediction/ReadMe.md
  DogBreedPrediction/app.py
  DogBreedPrediction/breed_prediction.h5
  DogBreedPrediction/dog.png
  DogBreedPrediction/png-transparent.png
Labels: level3, gssoc23

#2511 Power Plant Energy Output Prediction Artificial Neural Network
  Power Plant Energy Output Prediction Neural Network/PowerPlantEnergyPrediction.ipynb
  Power Plant Energy Output Prediction Neural Network/dataset/df.csv
Labels: level3, gssoc23

#2514 Backup Generator
  Backup Generator/backup_generator.py
  Backup Generator/readme.md
Labels: level2, gssoc23

#2520 Maze.py
  AI-based AI Maze Solver/README.md
  AI-based AI Maze Solver/maze.py
Labels: level2, gssoc23

#2521 Reversi.py
  AI-driven AI Reversi/README.md
  AI-driven AI Reversi/Reversi.py
Labels: level2, gssoc23

#2524 2048.py
  AI-driven 2048(New game)/2048.py
  AI-driven 2048(New game)/README.md
Labels: level2, gssoc23

#2523 Tron.py
  AI-driven AI Tron/README.md
  AI-driven AI Tron/Tron.py
Labels: level2, gssoc23

#2522 Flappy_bird.py
  AI-driven AI Flappy Bird/Flappy_bird.py
  AI-driven AI Flappy Bird/README.md
Labels: level2, gssoc23

#2527 Added Trading view Python Script
  TradingView/LICENSE
  TradingView/NOTES.rst
  TradingView/README.md
  TradingView/cli/fixtool
  TradingView/fixtool-agent
  TradingView/python/fixtool/__init__.py
  TradingView/python/fixtool/agent.py
  TradingView/python/fixtool/message.py
  TradingView/python/fixtool/proxy.py
  TradingView/python/fixtool/version.py
  TradingView/python/tests/test_basic.py
  TradingView/requirements.txt
  TradingView/setup.py
Labels: level2, gssoc23

#2542 feat: improve seo of entire amazing python scripts website 🚀✨
  index.html
Labels: level2, gssoc23

#2544 refactor: contributors.js with best practices ✨
  js/contributors.js
Labels: level2, gssoc23

#2546 AI Language Learning Assistant Script Added
  AI Language Learning Assistant/README.md
  AI Language Learning Assistant/language_learning_assistant.py
  AI Language Learning Assistant/requirements.txt
Labels: level2, gssoc23

#2549 Added Gender Recognition Using Voice
  Gender Recognition Using Voice/README.md
  Gender Recognition Using Voice/code.ipynb
  Gender Recognition Using Voice/dataset.csv
Labels: level2, gssoc23

#2555 AI-based Chatbot for Diverse Topics Script Added
  AI-based Chatbot for Diverse Topics/README.md
  AI-based Chatbot for Diverse Topics/chatbot.py
  AI-based Chatbot for Diverse Topics/requirements.txt
Labels: level2, gssoc23

#2558 Added Computer Details Script
  Computer-Details/README.md
  Computer-Details/computer-details.py
  Computer-Details/output.png
  Computer-Details/requirements.txt
Labels: level2, gssoc23

#2752 Hang man game completed ( #2750)
  Hang man game/README.md
  Hang man game/hangman.py
Labels: level3, gssoc23

#2569 Air Quality Index Predictor Deployed ML Model
  Air Quality Index Prediction/AQIPrediction.ipynb
  Air Quality Index Prediction/ReadMe.md
  Air Quality Index Prediction/app.py
  Air Quality Index Prediction/city_day.csv
  Air Quality Index Prediction/label_encoder.pkl
Labels: level3, gssoc23

#2758 Mastermind game ( #2757)
  Mastermind game/README.md
  Mastermind game/game.py
Labels: level3, gssoc23

#2571 KenKen Puzzle Solver Script Added
  KenKen Puzzle Solver/README.md
  KenKen Puzzle Solver/kenken_puzzle_solver.py
  KenKen Puzzle Solver/requirements.txt
Labels: level2, gssoc23

#2573 object detection - template matching
  Object detection in Image/ReadMe.md
  Object detection in Image/Sample_Image.png
  Object detection in Image/Sample_Output.png
  Object detection in Image/Sample_Template.png
  Object detection in Image/template_matching.py
Labels: level2, gssoc23

#2576 PDF Merger Script
  PDF_Merger/README.md
  PDF_Merger/pdfmerger.py
Labels: level2, gssoc23

#2582 Personal Finance Manager Script Added
  Personal Finance Manager/README.md
  Personal Finance Manager/personal_finance_manager.py
  Personal Finance Manager/requirements.txt
Labels: level3, gssoc23

#2528 web scraping property websites like MagicBricks
  WebScrapingPropertyWebsite/ReadMe.md
  WebScrapingPropertyWebsite/web_scraping(magicbricks).py
Labels: level2, gssoc23

#2583 Back to top button updated
  index.html
Labels: level1, gssoc23

#2589 video reversing
  Video reversing/ReadMe.md
  Video reversing/sampleOutput.mp4
  Video reversing/sampleVideo.mp4
  Video reversing/video_reversing.py
Labels: level2, gssoc23

#2597 Port Scanner Python Script
  port scanner/ReadMe.txt.txt
  port scanner/port_scanner.py
Labels: level2, gssoc23

#2598 border extraction
  Border Extraction/Border_extraction.py
  Border Extraction/Output.png
  Border Extraction/ReadMe.md
  Border Extraction/sample.png
Labels: level2, gssoc23

#2602 Sentiment analysis script added - GSSOC'23
  SCRIPTS.md
  Sentiment Analysis/README.md
  Sentiment Analysis/Sentiment_Analysis.py
  Sentiment Analysis/data.csv
Labels: level2, gssoc23

#2605 Cryptocurrency Intermarket Analysis ML Model
  Cryptocurrency Intermarket Analysis ML Model/CryptoIntermarketAnalysis.ipynb
  Cryptocurrency Intermarket Analysis ML Model/ReadMe.txt.txt
Labels: level2, gssoc23

#2608 Automated script
  Automated Script/Script.py
Labels: level2, gssoc23

#2609 Create script.py
  Lyrics Finder /script.py
Labels: level2, gssoc23

#2615 Create Dice_Rolling.py
  Dice Rolling Game/Dice_Rolling.py
  Dice Rolling Game/README.md
Labels: level2, gssoc23

#2616 Create Drag.py
  Drag Racing Game/Drag.py
  Drag Racing Game/README.md
Labels: level2, gssoc23

#2622 Reverse Tower Defense Game Script Added
  Reverse Tower Defense Game/README.md
  Reverse Tower Defense Game/requirements.txt
  Reverse Tower Defense Game/reverse_tower_defense.py
Labels: level2, gssoc23

#2623 blending of images
  Blending Images/Output_0.5_alpha.jpg
  Blending Images/ReadMe.md
  Blending Images/blending_Image.py
  Blending Images/lake.jpg
  Blending Images/lotus.jpg
Labels: level2, gssoc23

#2625 Draw.py
  Drawing Guess AI/README.md
  Drawing Guess AI/drawing.py
Labels: level2, gssoc23

#2627 Puzzle.py
  Door Puzzle AI/Puzzle.py
  Door Puzzle AI/README.md
Labels: level2, gssoc23

#2649 applying borders to images
  Image borders/Image_border.py
  Image borders/ReadMe.md
  Image borders/exampleOutput.png
  Image borders/flower.jpg
Labels: level2, gssoc23

#2654 Pattern Recognition Game Script Added
  Pattern Recognition Game/README.md
  Pattern Recognition Game/pattern_recognition_game.py
  Pattern Recognition Game/requirements.txt
Labels: level2, gssoc23

#2656 Haunted House Text Adventure Game Script Added
  Haunted House Text Adventure Game/README.md
  Haunted House Text Adventure Game/haunted_house_game.py
  Haunted House Text Adventure Game/requirements.txt
Labels: level2, gssoc23

#2658 Only using python
  Portfolio/README.md
  Portfolio/index.py
Labels: level2, gssoc23

#2662 GuesstheWordGame.py
  Guess the Word Game/GuesstheWordGame.py
  Guess the Word Game/README.md
Labels: level2, gssoc23

#2666 Grid_Explorer.py
  Grid Explorer/Grid_Explorer.py
  Grid Explorer/README.md
Labels: level2, gssoc23

#2667 Game_of_Fifteen.py
  Game of Fifteen/Game_of_Fifteen.py
  Game of Fifteen/README.md
Labels: level2, gssoc23

#2669 added Youtube Video Scraper
  YouTube-Scraper/README.md
  YouTube-Scraper/requirements.txt
  YouTube-Scraper/video.py
Labels: level3, gssoc23

#2676 website using html css and python flask
  BMI Calculator/README.md
  BMI Calculator/app.py
  BMI Calculator/styles.css
  BMI Calculator/templates/index.html
  BMI Calculator/templates/result.html
Labels: level2, gssoc23

#2681 Stock Price Direction Prediction ML Model
  Stock Price Direction Prediction(Tesla)/ReadMe.txt
  Stock Price Direction Prediction(Tesla)/StockTradingForecasting.ipynb
Labels: level3, gssoc23

#2799 Image Downloader GUI
  Image Downloader GUI/ReadMe.md
  Image Downloader GUI/dog.jpg
  Image Downloader GUI/main.py
Labels: level2, gssoc23

#2796 Website Status Checker GUI
  Website Status Checker GUI/ReadMe.md
  Website Status Checker GUI/app.py
Labels: level2, gssoc23

#2794 AI Driven Storytelling Game Script Added
  AI Driven Storytelling Game/README.md
  AI Driven Storytelling Game/ai-storytelling-game.py
  AI Driven Storytelling Game/requirements.txt
Labels: level2, gssoc23

#2791 Automated Game Testing Framework Script Added
  Automated Game Testing Framework/README.md
  Automated Game Testing Framework/game_testing_framework.py
  Automated Game Testing Framework/requirements.txt
Labels: level3, gssoc23

#2783 Dynamic Music Generator Script Added
  Dynamic Music Generator/README.md
  Dynamic Music Generator/dynamic_music_generator.py
  Dynamic Music Generator/requirements.txt
Labels: level2, gssoc23

#2780 Income Predicting using Random Forest Classifier and Exploratory Data Analysis of the income dataset
  Income Predictive Modelling + EDA/Income_Prediction+EDA.ipynb
  Income Predictive Modelling + EDA/ReadMe.md
  Income Predictive Modelling + EDA/dataset/income_data.csv
Labels: level3, gssoc23

#2778 [GSSoC'23] All Convertors Application ✔️
  All-Convertors/Convertors.py
  All-Convertors/README.md
  SCRIPTS.md
Labels: level2, gssoc23

#2777 Algorithmic Trading Simulation Script Added
  Algorithmic Trading Simulation/README.md
  Algorithmic Trading Simulation/algorithmic_trading_simulation.py
  Algorithmic Trading Simulation/requirements.txt
Labels: level2, gssoc23

#2775 Procedural Dungeon Generator Script Added
  Procedural Dungeon Generator/README.md
  Procedural Dungeon Generator/dungeon_generator.py
  Procedural Dungeon Generator/requirements.txt
Labels: level2, gssoc23

#2772 [GSSoC'23] Complaint Management Program ✔️
  Complaint-Management/README.md
  Complaint-Management/db.py
  Complaint-Management/information.db
  Complaint-Management/listComp.py
  Complaint-Management/main.py
  SCRIPTS.md
Labels: level2, gssoc23

#2771 Codebreaker Game with AI Script Added
  Codebreaker Game with AI/README.md
  Codebreaker Game with AI/codebreaker_game.py
  Codebreaker Game with AI/requirements.txt
Labels: level2, gssoc23

#2743 Multi-Factor Authentication Generator script added
  Multi-Factor Authentication (MFA) Generator/README.md
  Multi-Factor Authentication (MFA) Generator/multi_factor_auth.py
  Multi-Factor Authentication (MFA) Generator/requirements.txt
Labels: level2, gssoc23

#2741 Telegram Get-Group-Members Bot
  Telegram Get-Group-Members Bot/readme.md
  Telegram Get-Group-Members Bot/requirements.txt
  Telegram Get-Group-Members Bot/telegram.py
Labels: level2, gssoc23

#2739 Email-Scheduler
  Email-Scheduler/Email_scheduler.py
  Email-Scheduler/readme.md
Labels: level2, gssoc23

#2738 Titanic Survival Prediction ML Model(CatBoostClassifier)
  Titanic Survival Prediction/ReadMe.txt
  Titanic Survival Prediction/Titanic_Survival_Prediction.ipynb
  Titanic Survival Prediction/dataset/titanic3.csv
Labels: level2, gssoc23

#2716 foreground extraction from images
  Foreground Extraction/ReadMe.md
  Foreground Extraction/Sample_Image.jpg
  Foreground Extraction/Sample_Output.png
  Foreground Extraction/Sample_Selection.png
  Foreground Extraction/foregroundExtraction.py
Labels: level2, gssoc23

#2711 Pnuemonia Detection with Convolutional Neural Networks(CNN)
  Pnemonia Detection(CNNs)/ReadMe.txt
  Pnemonia Detection(CNNs)/pnuemonia-detection-cnns.ipynb
Labels: level2, gssoc23

#2710 Predicting Insurance Charges ML Model and Exploratory Data Analysis
  Predicting Insurance Charges (Linear Regression)/InsuranceAmountPrediction.ipynb
  Predicting Insurance Charges (Linear Regression)/ReadMe.txt
  Predicting Insurance Charges (Linear Regression)/dataset/insurance.csv
Labels: level2, gssoc23

#2694 Movie Recommender Systems
  movie recommender systems/Movie_Recommender_Systems.ipynb
  movie recommender systems/dataset/movie_metadata.csv
  movie recommender systems/readme.txt
Labels: level2, gssoc23

#2685 Fashion MNIST MultiClass Image Classification using Convolutional Neural Networks (CNN)
  Fashion MNIST MultiClass Image Classification  (CNN)/Fashion_MNIST_MultiClass_Image_Classification_(CNN).ipynb
  Fashion MNIST MultiClass Image Classification  (CNN)/ReadMe.md
Labels: level3, gssoc23

#2683 Cats Vs Dogs Image Classification Using CNNs
  Cats Vs Dog Image Classifier (CNN)/CatVsDogs.ipynb
  Cats Vs Dog Image Classifier (CNN)/ReadMe.md
  Cats Vs Dog Image Classifier (CNN)/pngwing.com (1).png
Labels: level2, gssoc23

#2839 Netflix Userbase EDA
  Netflix UserBase EDA/NetflixUserBaseEDA.ipynb
  Netflix UserBase EDA/ReadMe.txt
  Netflix UserBase EDA/dataset/Netflix Userbase.csv
Labels: level2, gssoc23

#2840 File Sorter GUI
  File Sorter GUI/ReadMe.txt
  File Sorter GUI/app.py
Labels: level2, gssoc23

#2846 Tic Tac Toe(AI) terminal game
  Terminal Tic Tac Toe(AI)/app.py
  Terminal Tic Tac Toe(AI)/readme.txt
Labels: level2, gssoc23

#2855 Common Password Checker GUI
  Common Password Checker/ReadMe.txt
  Common Password Checker/app.py
  Common Password Checker/pwd.txt
Labels: level2, gssoc23

#2856 Zoombinis.py
  Zoombinis/README.md
  Zoombinis/Zoombinis.py
Labels: level2, gssoc23

#2858 MNIST Handwritten Digit Recognition using Convolutional Neural Networks (CNNs)
  MNIST Digits Classification(CNN)/Handwritten_Digit_Recognition_using_Convolutional_Neural_Networks_(CNNs).ipynb
  MNIST Digits Classification(CNN)/ReadMe.txt
Labels: level2, gssoc23

#2860 EDA Iris dataset
  EDA Iris Datset/EDA_Iris_Datset.ipynb
  EDA Iris Datset/ReadME.txt
Labels: level2, gssoc23

#2864 Anagram Finder GUI
  AnagramFinder(GUI)/ReadMe.txt
  AnagramFinder(GUI)/app.py
Labels: level2, gssoc23

#2866 Image to ASCII Art Converter
  Image to ASCII Art/app.py
  Image to ASCII Art/pngwing.com (1).png
  Image to ASCII Art/readme.txt
Labels: level2, gssoc23

#2868 Convolutional Neural networks on CIFAR-10 dataset
  CIFAR 10(CNN)/CIFAR_10_CNN_.ipynb
  CIFAR 10(CNN)/ReadMe.txt
Labels: level2, gssoc23

#2870 Boston Housing Price Prediction with CatBoost
  Predicting Boston Housing Prices using CatBoost Regression/Predicting_Boston_Housing_Prices_using_CatBoost_Regression (1).ipynb
  Predicting Boston Housing Prices using CatBoost Regression/ReadME.txt
Labels: level2, gssoc23

#2874 Folder Locker and Hider script added
  Folder_locker_and_Hider/Folder_locker_and_Hider .py
  Folder_locker_and_Hider/README.md
Labels: level2, gssoc23

#2879 [ADDED]: Workflow for Close Issue if Opener has Opened Issues
  .github/workflows/.github/workflows/prevent_multiple_issues.yml
Labels: level2, gssoc23

#2888 Amazon Price Tracker
  Amazon Price Tracker/script.py
Labels: level2, gssoc23

#2889 Iris Flower Species Classification using Neural Networks
  Iris Flower Species Classification using Neural Networks/IrisDataset(Neural_Networks).ipynb
  Iris Flower Species Classification using Neural Networks/readme.txt
Labels: level2, gssoc23

#2890 Amazon Wishlist Notifier
  Amazon Wishlist Notifier/script.py
Labels: level2, gssoc23

#2892 perspective transformation
  Perspective_transform/ReadMe.md
  Perspective_transform/Sample.png
  Perspective_transform/Transformed Image.png
  Perspective_transform/perspective_transform.py
Labels: level2, gssoc23

#2906 Added Pixabay Image Scraper
  Pixabay Scraper/README.md
  Pixabay Scraper/main.py
Labels: level3, gssoc23

#2934 Added CNN web scraper
  CNN Scraper/README.md
  CNN Scraper/cnn.py
  CNN Scraper/requirements.txt
Labels: level3, gssoc23

#2929 Cryptic Language Puzzle Script Added
  Cryptic Language Puzzle Game/README.md
  Cryptic Language Puzzle Game/cryptic_language_game.py
Labels: level2, gssoc23

#2927 Adjective Comparative and Superlative Generator using NLP
  Adjective Comparative and Superlative Generator using NLP/ReadMe.txt
  Adjective Comparative and Superlative Generator using NLP/script.py
Labels: level2, gssoc23

#2924 added Google News Scraper
  GoogleNews-Scraper/README.md
  GoogleNews-Scraper/googleNews.py
  GoogleNews-Scraper/requirements.txt
Labels: level2, gssoc23

#2921 N-Grams Generation Script using NLTK(NLP)
  N-Grams NLP/ReadMe.txt
  N-Grams NLP/script.py
Labels: level2, gssoc23

#2916 Spell Correction Script using NLP
  Spell Correction (NLP)/ReadMe.txt
  Spell Correction (NLP)/script.py
Labels: level2, gssoc23

#2914 Word Singularization and Pluralization using NLP
  Singularize and Pluralize using NLP/ReadMe.txt
  Singularize and Pluralize using NLP/script.py
Labels: level2, gssoc23

#2912 Graph Neural Network(GNNs) for Node Classification
  GNN for Node Classification/Graph_Neural_Network_for_Node_Classification.ipynb
  GNN for Node Classification/ReadMe.txt
Labels: level2, gssoc23

#2909 [ADDED]: Lock new Issues workflow
  .github/workflows/lock.yml
Labels: level2, gssoc23

#2986 Created readme examples
  AI Calculator/README.md
  Air pollution prediction/README.md
  Automated_scraper.py/readme.md
Labels: level3, Approved
