Repository avinashkranjan/Amazing-Python-Scripts, pull requests merged in 2023-05, with the labels that each got.

#1430 Refactored the code in Stone-Paper-Scissors-Game
  Keylogger/keylogger.py
  Stone-Paper-Scissors-Game/Rock-Paper-Scissors Game.py
Labels: level2, gssoc23

#1541 Search Bot
  Search Bot/ReadMe.md
  Search Bot/Search_Bot.ipynb
  Search Bot/requirements.txt
Labels: level3, gssoc23

#1457 Updated README Content and Updated Script of CPU TEMPERATURE
  CPU temperature/Readme.md
  CPU temperature/temp.py
Labels: level1, gssoc23

#1565 Railway reservation system #1533
  railway reservation system/PYTHON PROJECT(FINAL).py
  railway reservation system/railway_bookings.sql
  railway reservation system/railway_customer_details.sql
  railway reservation system/railway_train.sql
  railway reservation system/railway_train_manager.sql
Labels: level3, gssoc23

#1459 Updated the readme file for Plagiarism checker.
  Plagiarism-Checker/README.md
Labels: level1, gssoc23

#1567 Update main.py
  Discord-Bot/main.py
Labels: level1, gssoc23
