Repository avinashkranjan/Amazing-Python-Scripts, pull requests merged in 2023-06, with the labels that each got.

#1576 Added Language Translator
  Language Translator/README.md
  Language Translator/lanaguage_translator.py
Labels: level3, gssoc23

#1661 Updated README.md
  face_detection/README.md
Labels: level1, gssoc23

#1618 Added contrast and inversion to Photo to ASCII
  Photo To Ascii/photo_to_ascii.py
Labels: level2, gssoc23

#1588 port scanner commit
  PortScanning/portscanningscript.py
Labels: level2, gssoc23

#1594 Add Multi Language Translation
  Multi-Language Translation/README.md
  Multi-Language Translation/main.py
  Multi-Language Translation/requirements.txt
Labels: level2, gssoc23

#1642 Added qrcode generator
  QR-Code-Generator/QR-generator.py
  QR-Code-Generator/readme.md
  QR-Code-Generator/requirements.txt
Labels: level2, gssoc23

#1643 [GSSOC'23] Time Zone converter in Tkinter GUI
  Timezone Converter GUI/Readme.md
  Timezone Converter GUI/Tkinter_time_conv.py
Labels: level2, gssoc23

#1631 ISSUE [#1551] WEBSCARPING OF FILPKART MOBILE PHONE UNDER 50K
  Flipkart_webscraping/Scrap.py
  Flipkart_webscraping/Steps.txt
  Flipkart_webscraping/filpkart-Scraping-under-50k.csv
Labels: level3, gssoc23

#1646 Create Age_Calculator.py
  Age_Calculator/Age_Calculator.py
  Age_Calculator/README.md
Labels: level1, gssoc23

#1600 Added necessary files
  Face_Detection_using_openCV/README.md
  Face_Detection_using_openCV/script.py
Labels: level3, gssoc23

#1651 UI of Script card updated
  css/scripts.css
Labels: level2, gssoc23

#1656 [SCRIPTS] Added Basic Data Structures Scripts (#1421)
  Linked List/Menu_Driven_Code_for_Circular_Doubly_LinkedList.py
  Linked List/Menu_Driven_Code_for_Circular_LinkedList.py
  Linked List/Menu_Driven_Code_for_Doubly_LinkedList.py
  Linked List/Menu_Driven_Code_for_Dynamic_Linear_Queue_using_LinkedList.py
  Linked List/Menu_Driven_Code_for_Dynamic_Stack_using_LinkedList.py
  Linked List/Menu_Driven_Code_for_Linear_LinkedList.py
  Linked List/README.md
  Queue/Menu_Driven_Code_for_Circular_Queue.py
  Queue/Menu_Driven_Code_for_Dynamic_Linear_Queue_using_LinkedList.py
  Queue/Menu_Driven_Code_for_Linear_Queue.py
  Queue/Menu_Driven_Code_for_Priority_Queue.py
  Queue/README.md
  SCRIPTS.md
  Searching Techniques/Binary_Search_Iterative.py
  Searching Techniques/Binary_Search_Recursive.py
  Searching Techniques/README.md
  Searching Techniques/Sequential_Search.py
  Sorting Techniques/Bubble_Sort.py
  Sorting Techniques/Insertion_Sort.py
  Sorting Techniques/Merge_Sort.py
  Sorting Techniques/Quick_Sort.py
  Sorting Techniques/README.md
  Sorting Techniques/Selection_Sort.py
  Stack/Menu_Driven_Code_for_Dynamic_Stack_using_LinkedList.py
  Stack/Menu_Driven_Code_for_Stack.py
  Stack/README.md
Labels: level3, gssoc23

#1660 Added GUI and Readme file
  Weather-App/README.md
  Weather-App/weatherapp.py
Labels: level2, gssoc23

#1572 Playback-speed-Calculator
  Playback-speed-calculator/Playback-speed-calculator.py
  Playback-speed-calculator/readme.md
Labels: level2, gssoc23

#1571 [GSSoC 23'] GUI Login Page Addition with credential checking mechanism
  CustomTkinter-GUI/SignUP_page/README.md
  CustomTkinter-GUI/SignUP_page/SignUP.py
Labels: level2, gssoc23

#1668 Exception Handling in Data Visualization
  Data-Visualization/LineChart/line_chart.py
Labels: level2, gssoc23

#1665 Added files for Morse-Code-Translator-GUI
  Morse-Code-Translator-GUI/README.md
  Morse-Code-Translator-GUI/main.py
  Morse-Code-Translator-GUI/screenshots/tkinter-working.gif
Labels: level2, gssoc23

#1613 Flappy Bird Game Agent
  AI TicTacToe/src/TicTacToe.py
  FlappyBird/.vscode/settings.json
  FlappyBird/Flappy.py
  FlappyBird/README.md
  FlappyBird/flappybrain.h5
Labels: level3, gssoc23

#1612 Added script to delete all your tweets
  Tweet Deleter/README.md
  Tweet Deleter/delete_tweets.py
Labels: level3, gssoc23

#1605 'Fixed_half_input_statement'
  Age-Calculator-GUI/age_calc_gui.py
Labels: level1, gssoc23

#1602 Added the snake game
  TheSnakeGame/Readme.md
  TheSnakeGame/snake.py
Labels: level3, gssoc23

#1593 Update tree.py
  Directory Tree Generator/tree.py
Labels: level2, gssoc23

#1591 Fingers Count using OpenCV
  Finger_count_openCV/README.md
  Finger_count_openCV/main.py
  Finger_count_openCV/requirements.txt
Labels: level3, gssoc23

#1604 Updated Fibonacci.py using recursion
  Fibonacci_Sequence_Generator/Fibonacci.py
Labels: level2, gssoc23

#1676 Added Flappy bird game files
  Flappy-Bird-Game/README.md
  Flappy-Bird-Game/assets/audio/die.ogg
  Flappy-Bird-Game/assets/audio/die.wav
  Flappy-Bird-Game/assets/audio/hit.ogg
  Flappy-Bird-Game/assets/audio/hit.wav
  Flappy-Bird-Game/assets/audio/point.ogg
  Flappy-Bird-Game/assets/audio/point.wav
  Flappy-Bird-Game/assets/audio/swoosh.ogg
  Flappy-Bird-Game/assets/audio/swoosh.wav
  Flappy-Bird-Game/assets/audio/wing.ogg
  Flappy-Bird-Game/assets/audio/wing.wav
  Flappy-Bird-Game/assets/sprites/0.png
  Flappy-Bird-Game/assets/sprites/1.png
  Flappy-Bird-Game/assets/sprites/2.png
  Flappy-Bird-Game/assets/sprites/3.png
  Flappy-Bird-Game/assets/sprites/4.png
  Flappy-Bird-Game/assets/sprites/5.png
  Flappy-Bird-Game/assets/sprites/6.png
  Flappy-Bird-Game/assets/sprites/7.png
  Flappy-Bird-Game/assets/sprites/8.png
  Flappy-Bird-Game/assets/sprites/9.png
  Flappy-Bird-Game/assets/sprites/background-day.png
  Flappy-Bird-Game/assets/sprites/base.png
  Flappy-Bird-Game/assets/sprites/bluebird-downflap.png
  Flappy-Bird-Game/assets/sprites/bluebird-midflap.png
  Flappy-Bird-Game/assets/sprites/bluebird-upflap.png
  Flappy-Bird-Game/assets/sprites/gameover.png
  Flappy-Bird-Game/assets/sprites/message.png
  Flappy-Bird-Game/assets/sprites/pipe-green.png
  Flappy-Bird-Game/assets/sprites/redbird-downflap.png
  Flappy-Bird-Game/assets/sprites/redbird-midflap.png
  Flappy-Bird-Game/assets/sprites/redbird-upflap.png
  Flappy-Bird-Game/assets/sprites/yellowbird-downflap.png
  Flappy-Bird-Game/assets/sprites/yellowbird-midflap.png
  Flappy-Bird-Game/assets/sprites/yellowbird-upflap.png
  Flappy-Bird-Game/main.py
  Flappy-Bird-Game/screenshot.gif
Labels: level3, gssoc23

#1582 Updated Amazon-Price-Tracker
  Amazon-Price-Tracker/README.MD
  Amazon-Price-Tracker/amazonprice.py
  Amazon-Price-Tracker/requirements.txt
  Amazon-Price-Tracker/tempCodeRunnerFile.py
Labels: level2, gssoc23

#1620 Imag-to-PDF converter
  Image-to-PDF Converter/README.md
  Image-to-PDF Converter/main.py
Labels: level2, gssoc23

#1622 fixes #1519
  DSA-Python/Algorithms/BigO.md
  DSA-Python/Algorithms/BigO.py
  DSA-Python/Algorithms/BinarySearch.py
  DSA-Python/Algorithms/BinarySearchTree.py
  DSA-Python/Algorithms/BubbleSort.py
  DSA-Python/Algorithms/InsertionSort.py
  DSA-Python/Algorithms/MergeSort.py
  DSA-Python/Algorithms/SelectionSort.py
  DSA-Python/Algorithms/ShellSort.py
  DSA-Python/Algorithms/recursion.py
  DSA-Python/DataStructures/Data Structure Image.png
  DSA-Python/DataStructures/LinkedList.py
  DSA-Python/DataStructures/StackClass.py
  DSA-Python/DataStructures/dictionary.py
  DSA-Python/DataStructures/graph.py
  DSA-Python/DataStructures/hashtable.py
  DSA-Python/DataStructures/list.py
  DSA-Python/DataStructures/queue.py
  DSA-Python/DataStructures/sets.py
  DSA-Python/DataStructures/stack.py
  DSA-Python/DataStructures/tree.py
  DSA-Python/DataStructures/tuple.py
Labels: level2, gssoc23

#1624 Python code to open a website multiple times in a single click
  .github/MultipleTimes_Website_opener/README.md
  .github/MultipleTimes_Website_opener/code.py
Labels: level2, gssoc23

#1626 Github User Info Scrapper
  Github_User_Info/README.md
  Github_User_Info/main.py
  Github_User_Info/requirements.txt
Labels: level3, gssoc23

#1585 Added sentiment analyzer program
  Sentiment Analyser/README.md
  Sentiment Analyser/RNN(w2v).ipynb
  Sentiment Analyser/Screenshot 2023-05-30 123233.png
  Sentiment Analyser/requirements.txt
  Sentiment Analyser/word2vec.ipynb
Labels: level3, gssoc23

#1595 Added script to scrape coursera
  Coursera Scraper/README.md
  Coursera Scraper/courses.py
  Coursera Scraper/requirements.txt
Labels: level3, gssoc23

#1685 Updated Step 6 in CONTRIBUTING.md.
  CONTRIBUTING.md
Labels: level1, gssoc23

#1693 added json-to-csv.py
  JSON-to-CSV/json-to-csv.py
  JSON-to-CSV/readme.md
Labels: level2, gssoc23

#1691 added clock.py
  Simple-Clock-Gui/clock.py
  Simple-Clock-Gui/readme.md
Labels: level2, gssoc23

#1713 Added image manipulation script
  Image Manipulation Script/README.md
  Image Manipulation Script/image_manipulation.py
  SCRIPTS.md
Labels: level3, gssoc23

#1708 Stopwatch app
  GUI-Stopwatch/readme.md
  GUI-Stopwatch/stopwatch.py
Labels: level2, gssoc23

#1723 Added link Scrapper
  Readme.md
  script.py
Labels: level3, gssoc23

#1711 customizable Password generator GUI
  GUI-Password-Generator/generator.py
  GUI-Password-Generator/readme.md
  GUI-Password-Generator/requirements.txt
Labels: level2, gssoc23

#1727 Anime multiple spaces bug
  Anime-Tracker/anime_tracker.py
Labels: level2, gssoc23

#1678 Adding Phone number Tracker Project
  Phone Number Tracker/Number.py
  Phone Number Tracker/readme.md
Labels: level2, gssoc23

#1754 Image-Resizing
  Image-Resizing/README.md
  Image-Resizing/requirements.txt
  Image-Resizing/resize.py
Labels: level2, gssoc23

#1781 Adding google search automation using python script
  .github/Automated GoogleSearch using Python/README.md
  .github/Automated GoogleSearch using Python/code.py
Labels: level3, gssoc23

#1786 GIF Creator Added
  GIF/README.md
  GIF/gifnew.py
Labels: level3, gssoc23

#1788 Adding Python Script for Automated File Download to specified path.
  .github/FileDownload Automationi/README.md
  .github/FileDownload Automationi/script.py
Labels: level3, gssoc23

#1800 Adding python script to convert audio input to text input.
  Audio to Text Convertor/README.md
  Audio to Text Convertor/code.py
Labels: level3, gssoc23

#1798 Automate Spotify Discover Weekly Playlist
  Spotify Playlist Automation/README.md
  Spotify Playlist Automation/config.py
  Spotify Playlist Automation/requirements.txt
  Spotify Playlist Automation/spotify_discover_weekly.py
Labels: level3, gssoc23

#1807 Telegram Weather Bot added
  Telegram-Weather-Bot/README.md
  Telegram-Weather-Bot/main.py
Labels: level3, gssoc23

#1797 Updated Calculator README.md
  Calculator/README.md
Labels: Level0, gssoc23

#1843 Modified Bitwise Code
  Applying Bitwise Operations/Applying Bitwise operations.py
Labels: level3, gssoc23

#1862 (GSSoC '23) Improved The code (Error Handling)
  Age_Calculator/Age_Calculator.py
Labels: level2, gssoc23

#1778 Updated the calculator with some extra functions [GSSOC '23]
  Binary-Calculator-GUI/script.py
Labels: level2, gssoc23

#1724 Add Character Sequence Selection in Photo To ASCII
  Photo To Ascii/photo_to_ascii.py
Labels: level2, gssoc23

#1869 [GSSoC 23'] Feedback GUI mechanism
  CustomTkinter-GUI/Feedback_GUI/Feedback.py
  CustomTkinter-GUI/Feedback_GUI/FeedbackGUI
  CustomTkinter-GUI/Feedback_GUI/README.md
Labels: level2, gssoc23

#1753 ADDED travel_destinations_scraper.py
  File Downloader Script/Travel Destination Scraper/README.md
  File Downloader Script/Travel Destination Scraper/travel_destinations_scraper.py
Labels: level3, gssoc23

#1748 Added the File Encryption/Decryption script
  File Encryption/Decryption script/README.md
  File Encryption/Decryption script/file_encryption.py
  SCRIPTS.md
Labels: level3, gssoc23

#1608 [GSSOC'23] To add code for Measuring Internet Speed
  Internet-Speed-Test/Internet-Speed-Test.md
  Internet-Speed-Test/README.md
  Internet-Speed-Test/main.py
Labels: level2, gssoc23

#1888 modify issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/script-addition.md
  .github/ISSUE_TEMPLATE/script-addition.yml
Labels: level2, gssoc23

#1867 added wikipedia scrapper
  Wiki_Scrapper/Deutsch.txt
  Wiki_Scrapper/README.md
  Wiki_Scrapper/Screenshot 2023-06-21 132230.png
  Wiki_Scrapper/Selena Gomez.txt
  Wiki_Scrapper/wiki_Scraper.py
Labels: level3, gssoc23

#1820 CSV-To-Excel Converter Added
  CSV-To-Excel/CSV-To-Excel.py
  CSV-To-Excel/README.md
Labels: level2, gssoc23

#1805 [GSSOC'23]Sudoku Game
  Sudoku_Game/READ_ME.md
  Sudoku_Game/sudoku.py
Labels: level3, gssoc23

#1918 Updated linter version
  .github/workflows/py_lint.yml
Labels: level2, gssoc23

#1921 [GSSoC'23] TOI Scrapper
  TOI_Scrapper/README.MD
  TOI_Scrapper/TOI_Scrapper.py
  TOI_Scrapper/requirements.txt
Labels: level3, gssoc23

#1916 Added dynamic resolution to Photo-to-ASCII
  Photo To Ascii/photo_to_ascii.py
Labels: level3, gssoc23

#1861 SpaceInvaders Agent
  SpaceInvader-Agent/README.md
  SpaceInvader-Agent/SpaceInvaders Agent.py
  SpaceInvader-Agent/dqn.h5f.index
Labels: level3, gssoc23

#1911 Robot Navigation
  Autonomous-Taxi-Agent/Autonomous TaxiAgent.py
  Autonomous-Taxi-Agent/README.md
Labels: level3, gssoc23

#1650 Added YouTube Downloader application to this repo
  Padra's YouTube Downloader/README.md
  Padra's YouTube Downloader/YouTube_Donlowder.py
Labels: level3, gssoc23

#1709 Background payload runner
  Background-Payload-Runner/readme.md
  Background-Payload-Runner/requirements.txt
  Background-Payload-Runner/run-payload.py
Labels: level2, gssoc23

#1979 [GSSoC'23] Chess Game Ready using PYTHON script
  Chess-Game/README.md
  Chess-Game/images/Chess-Game.png
  Chess-Game/images/black bishop.png
  Chess-Game/images/black king.png
  Chess-Game/images/black knight.png
  Chess-Game/images/black pawn.png
  Chess-Game/images/black queen.png
  Chess-Game/images/black rook.png
  Chess-Game/images/white bishop.png
  Chess-Game/images/white king.png
  Chess-Game/images/white knight.png
  Chess-Game/images/white pawn.png
  Chess-Game/images/white queen.png
  Chess-Game/images/white rook.png
  Chess-Game/main.py
  SCRIPTS.md
Labels: level2, gssoc23

#1909 [GSSoC'23] Scientific Calculator Project Completed
  SCRIPTS.md
  Scientific_Calculator/README.md
  Scientific_Calculator/Scientific_Calculator.png
  Scientific_Calculator/Scientific_Calculator.py
  Scientific_Calculator/calculator.ico
Labels: level2, gssoc23

#1756 Added image generation telegram bot
  AI_Image_Generator_Telegram_Bot/README.md
  AI_Image_Generator_Telegram_Bot/ai_bot.py
  AI_Image_Generator_Telegram_Bot/replicatess.png
  AI_Image_Generator_Telegram_Bot/requirements.txt
  AI_Image_Generator_Telegram_Bot/telegramBotScreenShot.png
Labels: level3, gssoc23

#1780 'Fixed_day_section'
  Age-Calculator-GUI/age_calc_gui.py
Labels: level1, gssoc23

#1789 'Fixed_name_section'
  Age-Calculator-GUI/age_calc_gui.py
Labels: level2, gssoc23

#1935 Added dot connect game
  Dot_Connect/DotConnect.py
  Dot_Connect/README.md
Labels: level2, gssoc23

#1841 Updated readme file for snake game gui
  Snake Game (GUI)/README.md
Labels: level1, gssoc23

#1881 Add CodeQL workflow
  .github/workflows/codeql.yml
Labels: level3, gssoc23

#1923 [GSSOC'23] Added Readme file for Webcam Image Capture
  Webcam-(imgcap)/README.md
Labels: level1, gssoc23

#1880 Update QR-generator.py
  QR-Code-Generator/QR-generator.py
Labels: level2, gssoc23

#1767 Updated Contact form fields to required
  page_contactUs.html
Labels: level1, gssoc23

#1738 Added the Login and signup File [GUI]
  Login And Signup GUI/README.md
  Login And Signup GUI/Screenshots/Capture.PNG
  Login And Signup GUI/Screenshots/Capture1.PNG
  Login And Signup GUI/Screenshots/Capture2.PNG
  Login And Signup GUI/images/back.png
  Login And Signup GUI/images/bg.png
  Login And Signup GUI/images/bg1.png
  Login And Signup GUI/images/bg2.png
  Login And Signup GUI/images/bg3.png
  Login And Signup GUI/images/exit.png
  Login And Signup GUI/images/imap.png
  Login And Signup GUI/images/login.png
  Login And Signup GUI/images/loginicon.png
  Login And Signup GUI/images/logo_white.png
  Login And Signup GUI/images/passicon.png
  Login And Signup GUI/images/register.png
  Login And Signup GUI/images/reset.png
  Login And Signup GUI/images/time.png
  Login And Signup GUI/images/xx.png
  Login And Signup GUI/login.py
  Login And Signup GUI/requirements.txt
Labels: level2, gssoc23

#1743 IOC script in python
  IOC_Scripts/script.py
Labels: level2, gssoc23

#1821 Update and rename greetings.yml to auto-comment.yml
  .github/workflows/auto-comment.yml
  .github/workflows/greetings.yml
Labels: level2, gssoc23

#1586 Have Added The Project - Number Plate Detection System
  Number Plate Detection System/main.py.py
  Number Plate Detection System/requirements.txt.txt
Labels: level3, gssoc23

#1597 Added AI Calculator
  AI Calculator/main.py
Labels: level2, gssoc23

#1969 Modified Script of age Calculator
  Age_Calculator/Age_Calculator.py
Labels: level1, gssoc23

#1764 Sending Emails With File Attachments
  Email-With-Files/sendemail.py
Labels: level3, gssoc23

#1878 [ADDED]: Stock-Price-Prediction
  Stock-Price-Prediction/README.md
  Stock-Price-Prediction/Stock-Price-Prediction-project-dashboard-2.gif
  Stock-Price-Prediction/stock_app.py
  Stock-Price-Prediction/stock_pred.py
Labels: level3, gssoc23

#1879 [GSSoC'23] Arbitary Quotes Generator
  Arbitary Quotes Generator/README.md
  Arbitary Quotes Generator/arbitary_quotes_generator.py
  Digital Clock/Clock.py
  Fibonacci_Sequence_Generator/Fibonacci.py
Labels: level2, gssoc23

#1905 WhatsApp bot using autogui
  WhatsAppSpammerBot/image.png
  WhatsAppSpammerBot/main.py
  WhatsAppSpammerBot/readme.md
  WhatsAppSpammerBot/requirements.txt
Labels: level2, gssoc23

#1906 Story generator script is added
  SCRIPTS.md
  Story_Generator/Readme.md
  Story_Generator/story_generator.py
Labels: level3, gssoc23

#1983 commit msg #1955
  Memory-game/animal.py
  Memory-game/app.py
  Memory-game/assets/chicken.png
  Memory-game/assets/cow.png
  Memory-game/assets/dog.png
  Memory-game/assets/duck.png
  Memory-game/assets/elephant.png
  Memory-game/assets/giraffe.png
  Memory-game/assets/hippo.png
  Memory-game/assets/panda.png
  Memory-game/game_config.py
  Memory-game/other_assets/matched.png
Labels: level2, gssoc23

#1940 Added `Image Scrapper`
  Auto-Linkedin /AutoLinkedIn.py
  Auto-Linkedin /README.md
  Image-Scraper/README.md
  Image-Scraper/scrape_images.py
Labels: level2, gssoc23

#1936 Adding new functionalities to CPU Temperature script (Closes Issue #1416)
  CPU temperature/Readme.md
  CPU temperature/temp.py
Labels: level1, gssoc23

#1927 Audio splitting script added - GSSOC'23
  Audio Splitting/README.md
  Audio Splitting/audio-split.py
  SCRIPTS.md
Labels: level3, gssoc23

#1915 Added chrome dinosaur game
  Chrome_Dinosaur_Game/Assets/Bird/Bird1.png
  Chrome_Dinosaur_Game/Assets/Bird/Bird2.png
  Chrome_Dinosaur_Game/Assets/Cactus/LargeCactus1.png
  Chrome_Dinosaur_Game/Assets/Cactus/LargeCactus2.png
  Chrome_Dinosaur_Game/Assets/Cactus/LargeCactus3.png
  Chrome_Dinosaur_Game/Assets/Cactus/SmallCactus1.png
  Chrome_Dinosaur_Game/Assets/Cactus/SmallCactus2.png
  Chrome_Dinosaur_Game/Assets/Cactus/SmallCactus3.png
  Chrome_Dinosaur_Game/Assets/Dino/DinoDuck1.png
  Chrome_Dinosaur_Game/Assets/Dino/DinoDuck2.png
  Chrome_Dinosaur_Game/Assets/Dino/DinoJump.png
  Chrome_Dinosaur_Game/Assets/Dino/DinoRun1.png
  Chrome_Dinosaur_Game/Assets/Dino/DinoRun2.png
  Chrome_Dinosaur_Game/Assets/Dino/DinoStart.png
  Chrome_Dinosaur_Game/Assets/Other/Cloud.png
  Chrome_Dinosaur_Game/Assets/Other/Track.png
  Chrome_Dinosaur_Game/README.md
  Chrome_Dinosaur_Game/dino.gif
  Chrome_Dinosaur_Game/main.py
Labels: level3, gssoc23

#1913 GSSOC'23 - Added python script to play hangman
  SCRIPTS.md
  hangman/Readme.md
  hangman/__pycache__/hangman_visual.cpython-38.pyc
  hangman/__pycache__/words.cpython-38.pyc
  hangman/hangman.py
  hangman/hangman_visual.py
  hangman/words.py
Labels: level2, gssoc23

#1907 [GSSoC'23] Fleury Algorithm Completed
  Fleury-Algorithm/Fleury_Algorithm.py
  Fleury-Algorithm/README.md
  Fleury-Algorithm/Screenshot.png
  SCRIPTS.md
Labels: level2, gssoc23

#1984 Added HandWritten Character Recognition Script
  Handwritten-Character-Recognition/Handwritten_character_recog.py
  Handwritten-Character-Recognition/README.md
  Handwritten-Character-Recognition/image/img-m.jpg
  Handwritten-Character-Recognition/image/img-r.jpg
  Handwritten-Character-Recognition/model_hand.h5
Labels: level3, gssoc23

#1746 Change1
  Sales-and-Order-Management-System/.gitignore
  Sales-and-Order-Management-System/Addtional_features.py
  Sales-and-Order-Management-System/Admin_menu.py
  Sales-and-Order-Management-System/README.md
  Sales-and-Order-Management-System/User_menu.py
  Sales-and-Order-Management-System/Userlogin.py
  Sales-and-Order-Management-System/icons/images.png
  Sales-and-Order-Management-System/images/61205.png
  Sales-and-Order-Management-System/images/Contacts-512.png
  Sales-and-Order-Management-System/images/Door_Out-512.png
  Sales-and-Order-Management-System/images/Invoice2.png
  Sales-and-Order-Management-System/images/accounts.jpg
  Sales-and-Order-Management-System/images/accounts.png
  Sales-and-Order-Management-System/images/change1.png
  Sales-and-Order-Management-System/images/changeuser.png
  Sales-and-Order-Management-System/images/door-icon-emergency-exit-sign-vector-20712466.jpg
  Sales-and-Order-Management-System/images/download (1).png
  Sales-and-Order-Management-System/images/download.png
  Sales-and-Order-Management-System/images/inventory.png
  Sales-and-Order-Management-System/images/invoice.png
  Sales-and-Order-Management-System/images/items.png
  Sales-and-Order-Management-System/images/logout2.png
  Sales-and-Order-Management-System/images/logout3.jpg
  Sales-and-Order-Management-System/images/logout4.png
  Sales-and-Order-Management-System/images/my_profile.png
  Sales-and-Order-Management-System/images/myprofile.png
  Sales-and-Order-Management-System/images/myprofile3.png
  Sales-and-Order-Management-System/images/profile.png
  Sales-and-Order-Management-System/images/sales.png
  Sales-and-Order-Management-System/images/user_change-512.png
  Sales-and-Order-Management-System/login.db
  Sales-and-Order-Management-System/main.py
  Sales-and-Order-Management-System/requirements.txt
Labels: level2, gssoc23

#1985 Nth-Fibonacci-Number-Generator Added
  Nth-Fibonacci-Number-Generator/Nth_Fibonacci_Generator.py
  Nth-Fibonacci-Number-Generator/README.md
Labels: level2, gssoc23

#1816 PDF rotation API script
  PDF-rotation-API/1.pdf
  PDF-rotation-API/README.md
  PDF-rotation-API/api.py
  PDF-rotation-API/final.pdf
Labels: level2, gssoc23
