Repository avinashkranjan/Amazing-Python-Scripts, pull requests merged in 2023-07, with the labels that each got.

#1975 Get live youtube stats
  Get-Live-Youtube-Video-Stats/README.md
  Get-Live-Youtube-Video-Stats/main.py
  Get-Live-Youtube-Video-Stats/requirements.txt
Labels: level2, gssoc23

#1997 added Script to check External IP Address
  Check_External_IP/Check_IP.py
  Check_External_IP/README.md
  SCRIPTS.md
Labels: level2, gssoc23

#1998 Added Smoke Detector
  Smoke_Detect/FlameDect/README.md
  Smoke_Detect/FlameDect/SmokeDect/SmokeDect-v0.1.py
  Smoke_Detect/FlameDect/SmokeDect/SmokeDect-v0.2.py
  Smoke_Detect/FlameDect/SmokeDect/SmokeDect-v0.3.py
  Smoke_Detect/FlameDect/SmokeDect/__init__.py
  Smoke_Detect/FlameDect/SmokeDect/smokeDect-v0.py
  Smoke_Detect/FlameDect/SmokeDect/t.py
  Smoke_Detect/FlameDect/__init__.py
  Smoke_Detect/FlameDect/flameDect-v.py
  Smoke_Detect/FlameDect/flameDect-v2-1.py
  Smoke_Detect/FlameDect/flameDect-v2.py
  Smoke_Detect/FlameDect/flameDection.py
  Smoke_Detect/FlameDect/tools/__init__.py
  Smoke_Detect/FlameDect/tools/extract_frames.py
  Smoke_Detect/FlameDect/tools/get_hog.py
  Smoke_Detect/FlameDect/tools/gray_cumsum.py
  Smoke_Detect/FlameDect/tools/reformate_video.py
  Smoke_Detect/FlameDect/tools/show_coordinate.py
  Smoke_Detect/FlameDect/tools/split_images.py
Labels: level3, gssoc23

#1999 GridSearchCV fucntion
  GridSearchCV/GridsearchCV.py
  GridSearchCV/README.md
  GridSearchCV/requirements.txt
Labels: level2, gssoc23

#2000 Added Word Embedding Using Pytorch (GSSOC '23: Issue: #1817)
  Word_Embedding_Using_Pytorch/README.md
  Word_Embedding_Using_Pytorch/Word_Emebedding_Pytorch_code.ipynb
  Word_Embedding_Using_Pytorch/alice_dataset.txt
Labels: level3, gssoc23

#2002 Added Tableau Style UI Script
  Tableau-Style-UI/Tableau_Style_UI.ipynb
  Tableau-Style-UI/sample_salaries.csv
Labels: level3, gssoc23

#2003 [GSSOC'23] Added Readme file for Football-Player-Club-Info
  Football-Player-Club-Info/README.md
  Football-Player-Club-Info/main.py
Labels: level1, gssoc23

#2004 Adding Color Guess-GUI [Issue #1866]
  Color Guess-GUI/Color_guess.py
  Color Guess-GUI/README.md
  Color Guess-GUI/Score.jpg
  Color Guess-GUI/Score_time.jpg
Labels: level2, gssoc23

#2008 Caesar Cipher
  Caesar-Cipher/README.md
  Caesar-Cipher/caesar_cipher.py
  Caesar-Cipher/requirements.txt
Labels: level2, gssoc23

#2010 commit msg #1965
  URL_Short/.dockerignore
  URL_Short/Dockerfile
  URL_Short/README.md
  URL_Short/Shortener/__init__.py
  URL_Short/Shortener/admin.py
  URL_Short/Shortener/apps.py
  URL_Short/Shortener/forms.py
  URL_Short/Shortener/migrations/__init__.py
  URL_Short/Shortener/models.py
  URL_Short/Shortener/serializers.py
  URL_Short/Shortener/services/__init__.py
  URL_Short/Shortener/services/madwire.py
  URL_Short/Shortener/services/rebrandly.py
  URL_Short/Shortener/templates/shortener/home.html
  URL_Short/Shortener/tests.py
  URL_Short/Shortener/views.py
  URL_Short/UrlShortener/__init__.py
  URL_Short/UrlShortener/settings.py
  URL_Short/UrlShortener/urls.py
  URL_Short/UrlShortener/wsgi.py
  URL_Short/manage.py
  URL_Short/pytest.ini
  URL_Short/requirements.txt
  URL_Short/run.sh
  URL_Short/setup.py
Labels: level3, gssoc23

#2013 Stack Overflow scraper added
  StackOverflow-Scraper/README.md
  StackOverflow-Scraper/questions.py
  StackOverflow-Scraper/requirements.txt
Labels: level2, gssoc23

#2020 Solved valueError in currency Converter
  Currency Convertor - GUI based/Currency_convertor_GUI.py
Labels: level2, gssoc23

#2025 added a file_separator script
  File_Separator/README.md
  File_Separator/file_separator.py
Labels: level2, gssoc23

#2026 Text To Sheets added
  Text To Sheets/README.md
  Text To Sheets/input.txt
  Text To Sheets/output.xlsx
  Text To Sheets/text-to-sheets.ipynb
Labels: level2, gssoc23

#2029 added Python Script to View All GitHub Repos 👍
  All_GitHub_Repos/README.md
  All_GitHub_Repos/all_github_repos.py
Labels: level2, gssoc23

#2030 Added Pose-Estimation directory with script and README
  Pose_Estimation_Using_OpenCV/PoseEstimation.py
  Pose_Estimation_Using_OpenCV/README.md
Labels: level3, gssoc23

#2031 added Python Script to Search for Specific Files
  Search_File/README.md
  Search_File/searching_specific_files.py
Labels: level2, gssoc23

#2032 Added pagination
  css/scripts.css
  js/scripts.js
  scripts.html
Labels: level2, gssoc23

#2033 Clean Up photo directory Added
  9_Typesof_Hash_Craker/9_Types_of_Hash_Cracker.py
  9_Typesof_Hash_Craker/README.md
  Clean_Up_Photo_Directory/Clean_Up_Photo_Directory.py
  Clean_Up_Photo_Directory/README.md
Labels: level2, gssoc23

#2050 Fix Script Cards
  css/scripts.css
  js/scripts.js
Labels: level2, gssoc23

#2057 Image Classification script added - GSSOC'23
  Image Classification/README.md
  Image Classification/image_classification.py
  SCRIPTS.md
Labels: level3, gssoc23

#2059 Salary Clustering
  K-Means-Clustering/K-means++_model.pkl
  K-Means-Clustering/README.md
  K-Means-Clustering/Salary Dataset/Salary.csv
  K-Means-Clustering/Unsupervised_Learning_.ipynb
Labels: level3, gssoc23

#2061 My branch
  QR_Code_Scanner/QR_codes/github.com.png
  QR_Code_Scanner/QR_codes/google.com.png
  QR_Code_Scanner/Readme.md
  QR_Code_Scanner/python_script.ipynb
  QR_Code_Scanner/requirements.txt
Labels: level2, gssoc23

#2062 Added Network scanner script
  Network Scanner/README.md
  Network Scanner/network-scanner.py
Labels: level2, gssoc23

#2063 Cryptography Algorithms to encrypt and decrypt
  Cryptography/Algorithms/Caesar-cipher.py
  Cryptography/Algorithms/Diffie-Hellman.py
  Cryptography/Algorithms/README.md
  Cryptography/Algorithms/RSA.py
  Cryptography/Algorithms/Substitution-cipher.py
Labels: level2, gssoc23

#2069 [GSSoC'23] ISBN number Validator project ready
  Auto-Linkedin /AutoLinkedIn.py
  Auto-Linkedin /README.md
  ISBN-Number-Validator/ISBN-Number.py
  ISBN-Number-Validator/README.md
  SCRIPTS.md
Labels: level2, gssoc23

#2071 Blurring an image
  Blur an Image/BlurImage.py
  Blur an Image/ReadMe.md
Labels: level2, gssoc23

#2076 added a book scraper script
  Book_Scraper/README.md
  Book_Scraper/assests/image-1.png
  Book_Scraper/assests/image.png
  Book_Scraper/book.py
  Book_Scraper/requirements.txt
Labels: level2, gssoc23

#2077 add sortingAlgoVisualizer
  SortingAlgoVisualizer/sortingAlgoVisualizer.py
Labels: level2, gssoc23

#2108 Flask Apis for Image comparisons
  Flask_Apis/.gitignore
  Flask_Apis/Image_recognition_from_File_format.py
Labels: level3, gssoc23

#2124 Face_recognition_api_Added
  Flask_Apis/Image_recognition_from_File_format.py
Labels: level2, gssoc23

#2234 Python script for Floating text visual effect.
  .github/Floating text effect/README.md
  .github/Floating text effect/script.py
Labels: level3, gssoc23

#2117 [Snyk] Security upgrade scipy from 1.5.0 to 1.10.0rc1
  Noise Reduction Script/requirements.txt
Labels: Stale

#2055 Added Temperature convertor GUI python script
  Added_temperature_convertor_GUI_python_script.py
Labels: level2, gssoc23

#2080 Added Image processing python script [GSSOC'23] #1883
  Image Processing and Computer Vision python script.ipynb
Labels: level3, Stale, gssoc23

#2097 added Automatic Spelling Checker & Corrector 👍
  Automatic_Spelling_Checker_Corrector/README.md
  Automatic_Spelling_Checker_Corrector/automatic_spelling_checker_corrector.py
  Automatic_Spelling_Checker_Corrector/input.txt
  Automatic_Spelling_Checker_Corrector/requirements.txt
  SCRIPTS.md
Labels: level2, Stale, gssoc23

#2100 Added Speech Emotion Recognition using Deep Learning Network Flow (Issue: #2005)
  Speech_Emotion_Recognition/README.md
  Speech_Emotion_Recognition/Speech_Emotion_Recognition_Code.ipynb
Labels: level3, Stale, gssoc23

#2101 added fetch_contributions.py ✅
  Fetch_Contributions/README.md
  Fetch_Contributions/fetch_contributions.py
  Fetch_Contributions/requirements.txt
  SCRIPTS.md
Labels: level2, Stale, gssoc23

#2103 added Find by lyrics python script 👍
  FindByLyrics/README.md
  FindByLyrics/lyricsscraper.py
  FindByLyrics/main.py
  FindByLyrics/requirements.txt
  SCRIPTS.md
Labels: level2, Stale, gssoc23

#2104 added GFG Article Downloader script ✅
  FindByLyrics/README.md
  FindByLyrics/lyricsscraper.py
  FindByLyrics/main.py
  FindByLyrics/requirements.txt
  GeeksForGeeks_Article_Downloader/README.md
  GeeksForGeeks_Article_Downloader/geeksforgeeks_article_downloader.py
  GeeksForGeeks_Article_Downloader/requirements.txt
  SCRIPTS.md
Labels: level2, Stale, gssoc23

#2109 [GSSoC'23] Auto LinkedIn Script Resolved
  Auto-Linkedin/Auto-LinkedIn.py
  Auto-Linkedin/README.md
Labels: level2, Stale, gssoc23

#2110 Internet Speed Checker
  Internet Speed Checker/ReadMe.md
  Internet Speed Checker/internet_speed.py
Labels: level2, Stale, gssoc23

#2111 Added files for a smart desktop assistant
  VoxiDesk-Smart Desktop Assistant/README.md
  VoxiDesk-Smart Desktop Assistant/main.py
Labels: level2, Stale, gssoc23

#2116 Update Template for README.md
  Template for README.md
Labels: Stale

#2125 Adding hexCalculator project
  hexCalculator/README.md
  hexCalculator/hexCalculator.py
Labels: level2, Stale, gssoc23

#2131 Added python IOT project [Detection]
  IOT/Jupyter/README.md
  IOT/Jupyter/inference.py
  IOT/Jupyter/intruder_detector_jupyter.ipynb
  IOT/Jupyter/intruder_detector_jupyter.py
  IOT/README.md
  IOT/UI/api/videoData.php
  IOT/UI/composer.json
  IOT/UI/composer.lock
  IOT/UI/index.html
  IOT/UI/readme.md
  IOT/UI/resources/css/counter.css
  IOT/UI/resources/css/timeline.css
  IOT/UI/resources/javascript/counter.js
  IOT/UI/resources/javascript/detection_alert.js
  IOT/UI/resources/javascript/timeline.js
  IOT/application/inference.py
  IOT/application/intruder_detector.py
  IOT/docs/images/architectural-diagram.png
  IOT/docs/images/intruder.png
  IOT/docs/images/jupyter.png
  IOT/docs/images/jupyter_code.png
Labels: level3, gssoc23

#2134 Tambola game
  tambola-game/README.md
  tambola-game/game.py
  tambola-game/game_.jpeg
  tambola-game/requirements.txt
Labels: level3, gssoc23

#2140 Adding whatsapp group message automation
  WhatsApp-Auto-Messenger/WhatsApp_Group_Message.py
Labels: level2, gssoc23

#2146 added Ask ubuntu scraper
  AskUbuntu-Scraper/README.md
  AskUbuntu-Scraper/questions.py
  AskUbuntu-Scraper/requirements.txt
Labels: level3, gssoc23

#2155 Update Age_Calculator.py @avinashkranjan
  Age_Calculator/Age_Calculator.py
Labels: Level0, gssoc23

#2149 Agriculture Optimisation ML Model with Frontend App (Issue #2070)
  Agriculture Optimization ML Model/ReadMe.md
  Agriculture Optimization ML Model/agriculture.ipynb
  Agriculture Optimization ML Model/data.xlsx
  Agriculture Optimization ML Model/streamlit.py
  Agriculture Optimization ML Model/templates/index.html
Labels: level3, gssoc23

#2152 automated_software_testing
  software_testing/README.md
  software_testing/software testing.py
Labels: level2, gssoc23

#2156 added the decimal to hexadecimal calculator file and readme.me file f…
  .deepsource.toml
  Age_Calculator/Age_Calculator.py
  Decimal-to-hexa-decimal/decimal_to_hexa.py
  Decimal-to-hexa-decimal/readme.md
Labels: level2, Stale, gssoc23

#2158 national flag animation
  National_Flag/README.md
  National_Flag/flag.py
Labels: level2, gssoc23

#2164 Crypt_Socket script is added
  Crypt_Socket/Readme.md
  Crypt_Socket/crypt_socket.py
  SCRIPTS.md
Labels: level2, Stale, gssoc23

#2165 DOH dig script is added
  Doh-Dig/Readme.md
  Doh-Dig/dog-dig.py
  SCRIPTS.md
Labels: level2, Stale, gssoc23

#2167 Palindrome Checker
  Palindrome Checker/README.md
  Palindrome Checker/image.png
  Palindrome Checker/main.py
Labels: level2, gssoc23

#2170 Improved Ui of the card designs issue resolved #1995
  css/scripts.css
  index.html
  js/scripts.js
Labels: Stale

#2172 Create Tweepy.py
  Twitter bot/Tweepy.py
Labels: level2, gssoc23

#2181 Added Voice recorder files
  Voice_Recorder/Images/mic.png
  Voice_Recorder/Images/screen.gif
  Voice_Recorder/Images/voice.png
  Voice_Recorder/README.md
  Voice_Recorder/main.py
Labels: level3, gssoc23

#2201 EDA on Global Living Cost issue #2079
  Living Cost EDA/EDA_LivingCostbyCountry.ipynb
  Living Cost EDA/ReadMe.md
  Living Cost EDA/dataset/cost-of-living.csv
Labels: level2, gssoc23

#2206 Added Zomato Menu Scrapper
  Zomato Data Scraper/README.md
  Zomato Data Scraper/main.py
  Zomato Data Scraper/requirements.txt
Labels: level3, gssoc23

#2207 added ai chat bot
  AI Chat Bot/README.md
  AI Chat Bot/main.py
  AI Chat Bot/requirements.txt
Labels: level2, gssoc23

#2208 NATO Alphabets
  NATO/README.md
  NATO/image.png
  NATO/main.py
Labels: level2, gssoc23

#2209 birthday wisher bot
  Birthday Wisher Bot/README.md
  Birthday Wisher Bot/birthday.csv
  Birthday Wisher Bot/image.png
  Birthday Wisher Bot/letter_1.txt
  Birthday Wisher Bot/letter_2.txt
  Birthday Wisher Bot/letter_3.txt
  Birthday Wisher Bot/main.py
  Birthday Wisher Bot/requirements.txt
Labels: level2, gssoc23

#2216 Added Reddit sentiment analysis
  Reddit-Sentiment-Analysis-using-Pytorch-main/README.md
  Reddit-Sentiment-Analysis-using-Pytorch-main/reddit-sentiment-analysis.ipynb
Labels: level3, gssoc23

#2153 Closes #2078 added torrent to drive dowloader
  Torrent to Drive Downloader/leech.ipynb
  Torrent to Drive Downloader/readme.md
Labels: level2, gssoc23

#2292 New Python Script Added
  Slot-Machine-Game/README.md
  Slot-Machine-Game/slotmachine.py
Labels: level2, gssoc23

#2451 new Api endpoint added which supports url format parameter
  Flask_Apis/Image_recognition_from_File_format.py
Labels: level3, gssoc23

#2322 Added the MIT License badge and a license section
  README.md
Labels: Stale

#2305 QR Code generator GUI
  QR Code generator GUI/generator.py
  QR Code generator GUI/readme.md
Labels: level2, gssoc23

#2308 added Script to Check Who is Online on Whatsapp ✅
  Online_on_Whatsapp/README.md
  Online_on_Whatsapp/online.py
  Online_on_Whatsapp/users.py
Labels: level2, gssoc23

#2310 added Script to check wifi speed ✅
  Wifi_Speed/README.md
  Wifi_Speed/wifi_speed.py
Labels: level2, gssoc23

#2311 added word meaning checker ✅
  Word_meaning/README.md
  Word_meaning/meaning.py
Labels: level2, gssoc23

#2313 Added [script]: rename-file by modified time
  Rename_by_time/main.py
  Rename_by_time/readme.md
Labels: level2, gssoc23

#2314 Number guess game
  Number-Guess-Game/Readme.md
  Number-Guess-Game/numberguess.py
Labels: level2, gssoc23

#2318 Added IP from Hostname Script
  IP from Hostname/README.md
  IP from Hostname/ip_from_hostname.py
  IP from Hostname/output.png
Labels: level2, gssoc23

#2319 added a youtube channel details scrapper
  Youtube_Scraper/README.md
  Youtube_Scraper/main.py
  Youtube_Scraper/requirements.txt
Labels: level2, gssoc23

#2320 Added a Telegram Book Bot
  Telegram_Book_Bot/README.md
  Telegram_Book_Bot/book.py
  Telegram_Book_Bot/main.py
  Telegram_Book_Bot/requirements.txt
Labels: level2, gssoc23

#2326 GeeksforGeeks Scrapper
  GeeksforGeeks-Scrapper/gfg.py
  GeeksforGeeks-Scrapper/readme.md
  GeeksforGeeks-Scrapper/requirements.txt
Labels: level2, gssoc23

#2329 Password Strength checker script added
  Password_Strength_checker/README.md
  Password_Strength_checker/password_strength_checker.py
Labels: level2, gssoc23

#2332 Hangman Gui Script Added
  Hangman_Gui/README.md
  Hangman_Gui/hangman_gui.py
Labels: level2, gssoc23

#2334 Ink Art Puzzle Adventure Script added
  Ink_art_puzzle_adv/README.md
  Ink_art_puzzle_adv/ink-art-puzzle-adv.py
  Ink_art_puzzle_adv/requirements.txt
Labels: level2, gssoc23

#2336 [ADDED]: LinkedIn Profile
  LinkedIn_Profile_Info/README.md
  LinkedIn_Profile_Info/google_API.py
  LinkedIn_Profile_Info/profile.py
  LinkedIn_Profile_Info/requirements.txt
Labels: level2, gssoc23

#2337 new txt file analyzer with sample txt file
  Text-File_Analyzer/Readme.md
  Text-File_Analyzer/analyzer.py
  Text-File_Analyzer/sample.txt
Labels: level2, gssoc23

#2339 Icc rankings scraper added
  Icc_ranking_scraper/README.md
  Icc_ranking_scraper/rankings.py
Labels: level2, gssoc23

#2341 Coding language learning game added
  Coding Language Learning Game/README.md
  Coding Language Learning Game/coding_language_learning_game.py
Labels: level2, gssoc23

#2349 Text based adventure game script added
  Text-based Adventure Game/README.md
  Text-based Adventure Game/text_based_adv_game.py
Labels: level2, gssoc23

#2367 Added number-conversion script
  Number Conversion/Output/hexa_to_binary.png
  Number Conversion/Output/octal_to_binary.png
  Number Conversion/Output/octal_to_decimal.png
  Number Conversion/Output/octal_to_hexa.png
  Number Conversion/README.md
  Number Conversion/converter_script.py
Labels: level2, gssoc23

#2355 Added Parkinson's Disease detection project
  Parkinson's disease/Parkinson's disease.ipynb
  Parkinson's disease/README.md
  Parkinson's disease/data.csv
Labels: level3, gssoc23

#2303 Guess_a_number.py
  AI_Guess_a_number/Guess_a_number.py
  AI_Guess_a_number/README.md
Labels: level2, gssoc23

#2304 Snake_pygame.py
  Pygame_Snake/README.md
  Pygame_Snake/snake_pygame.py
Labels: level2, gssoc23

#2325 Added Sky Detection
  AirObjects/README.md
  AirObjects/air.py
Labels: level2, gssoc23

#2357 Bus ticket generator script added
  Bus ticket generator/README.md
  Bus ticket generator/bus_ticket_generator_script.py
  Bus ticket generator/requirements.txt
Labels: level2, gssoc23

#2358 blob detection with dfs
  Blob Detection/BlobDetection.py
  Blob Detection/ReadMe.md
  Blob Detection/blobImg.png
Labels: level2, gssoc23

#2359 Line detection
  Line_Detection_HoughLine/HoughLine.py
  Line_Detection_HoughLine/ReadMe.md
Labels: level2, gssoc23

#2361 Added ChatBot
  .github/ChatBot/README.md
  .github/ChatBot/chat_patterns.py
  .github/ChatBot/chatbot.py
Labels: level2, gssoc23

#2369 added a swiggy scraper module
  Swiggy_Scraper/README.md
  Swiggy_Scraper/main.py
  Swiggy_Scraper/requirements.txt
Labels: level3, gssoc23

#2370 enhancement : Improved Submit Button UI
  css/page-contact.css
Labels: level2, gssoc23

#2371 Circle detection in images
  Circle_Detect_HoughCircle/HoughCircle.py
  Circle_Detect_HoughCircle/ReadMe.md
  Circle_Detect_HoughCircle/Sample.jpg
  Circle_Detect_HoughCircle/SampleOutput.jpg
Labels: level3, gssoc23

#2374 Market Campaign App
  Marketing Campaign App/.env.example
  Marketing Campaign App/app.py
  Marketing Campaign App/requirements.txt
Labels: level3, gssoc23

#2373 AI Based Music Composer Script Added
  AI Based Music Composer/README.md
  AI Based Music Composer/music_composer.py
  AI Based Music Composer/requirements.txt
Labels: level3, gssoc23

#2376 Maze Generator and solver Script added
  Maze Generator and Solver/README.md
  Maze Generator and Solver/maze_game.py
  Maze Generator and Solver/requirements.txt
Labels: level2, gssoc23

#2377 Added dark mode to website
  css/darkMode.css
  css/home.css
  css/scripts.css
  index.html
  js/mode.js
  page_contactUs.html
  scripts.html
Labels: level2, gssoc23

#2380 GitHub_Traffic Script is added
  Github_Traffic/Github_Traffic.py
  Github_Traffic/README.md
Labels: level2, gssoc23

#2386 Coding Puzzle Generator Script added
  Coding Puzzle Generator/README.md
  Coding Puzzle Generator/coding_puzzle_generator.py
Labels: level3, gssoc23

#2384 Nature Sound Generator Script Added
  Nature Sound Generator/README.md
  Nature Sound Generator/nature_sounds_generator.py
  Nature Sound Generator/requirements.txt
Labels: level3, gssoc23

#2387 Linkedin posts scrapper added
  Linkedin_Posts_Scrapper/Linkedin_Posts_Scrapper.py
  Linkedin_Posts_Scrapper/README.md
Labels: level3, gssoc23

#2415 Self-Organizing-Maps
  Self-Organizing-Map/README.md
  Self-Organizing-Map/Self_Organizing_Map.ipynb
  Self-Organizing-Map/dataset/Credit_Card_Applications.csv
Labels: level2, gssoc23

#2416 Youtube Writing Script
  YT Script Writing Tool/Youtube.jpg
  YT Script Writing Tool/app.py
  YT Script Writing Tool/requirements.txt
  YT Script Writing Tool/utils.py
Labels: level3, gssoc23

#2454 Adding code and README.md file for Random Quote generation from list
  Random Quote Generator/README.md
  Random Quote Generator/code.py
Labels: level3, gssoc23
